-- 代休の1年失効 / 既存環境向け差分
-- 有効期限 = 休日出勤日 + 1年（その日まで使用可）
-- 失効日   = 有効期限 + 1日

begin;

alter table public.holiday_work_records
  add column if not exists expired_days numeric not null default 0;


-- =========================================================
-- holiday_work_records CHECK変更
-- =========================================================

do $$
declare
  c record;
  v_found boolean := false;
begin
  for c in
    select
      conname,
      pg_catalog.pg_get_expr(conbin, conrelid) as expression
    from pg_catalog.pg_constraint
    where conrelid = 'public.holiday_work_records'::regclass
      and contype = 'c'
  loop
    if regexp_replace(
         c.expression,
         '[[:space:]()]',
         '',
         'g'
       ) = 'remaining_days=earned_days-used_days'
    then
      execute format(
        'alter table public.holiday_work_records drop constraint %I',
        c.conname
      );

      v_found := true;
    end if;
  end loop;

  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conrelid = 'public.holiday_work_records'::regclass
      and conname = 'holiday_work_expiration_balance_check'
  ) then

    if not v_found then
      raise exception 'expected_holiday_work_balance_check_not_found';
    end if;

    alter table public.holiday_work_records
      add constraint holiday_work_expiration_balance_check
      check (
        used_days >= 0
        and expired_days >= 0
        and remaining_days >= 0
        and used_days + expired_days <= earned_days
        and remaining_days =
          earned_days - used_days - expired_days
        and earned_days::text
          not in ('NaN','Infinity','-Infinity')
        and used_days::text
          not in ('NaN','Infinity','-Infinity')
        and expired_days::text
          not in ('NaN','Infinity','-Infinity')
        and remaining_days::text
          not in ('NaN','Infinity','-Infinity')
      ) not valid;
  end if;
end;
$$;

alter table public.holiday_work_records
  validate constraint holiday_work_expiration_balance_check;


-- =========================================================
-- 失効履歴
-- =========================================================

create table if not exists public.comp_leave_expirations (
  id bigint generated by default as identity primary key,

  holiday_work_record_id bigint
    not null
    unique
    references public.holiday_work_records(id),

  employee_id bigint
    not null
    references public.employees(id),

  work_date date not null,

  -- 最後に代休として使用できる日
  valid_until_date date not null,

  -- 実際に失効する日
  expiration_date date not null,

  expired_at timestamptz not null default now(),

  earned_days numeric not null,

  used_days_at_expiration numeric not null,

  expired_days numeric not null
    check (expired_days > 0),

  site_id bigint
    references public.sites(id)
    on delete set null,

  note text,

  created_at timestamptz not null default now()
);

alter table public.comp_leave_expirations
  enable row level security;

revoke all
on public.comp_leave_expirations
from public, anon, authenticated;

revoke all
on sequence public.comp_leave_expirations_id_seq
from public, anon, authenticated;

grant select
on public.comp_leave_expirations
to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'comp_leave_expirations'
      and policyname = 'comp_leave_expirations_manager_select'
  ) then

    create policy comp_leave_expirations_manager_select
    on public.comp_leave_expirations
    for select
    to authenticated
    using (
      public.is_leave_manager()
    );

  end if;
end;
$$;


-- =========================================================
-- 取得日が有効期限内で成立するか
-- =========================================================

create or replace function
public.comp_leave_dates_within_expiry(
  p_application_id bigint
)
returns boolean
language sql
volatile
security definer
set search_path = ''
as $$
  select

    exists (
      select 1
      from public.applications a
      where a.id = p_application_id
        and a.application_type = 'comp_leave'
    )

    and exists (
      select 1
      from public.comp_leave_dates d
      where d.application_id = p_application_id
    )

    and (
      select coalesce(sum(d.days), 0)
      from public.comp_leave_dates d
      where d.application_id = p_application_id
    )
    =
    (
      select coalesce(sum(ca.allocated_days), 0)
      from public.comp_leave_allocations ca
      where ca.application_id = p_application_id
    )

    and not exists (
      select 1
      from public.comp_leave_allocations ca

      join public.applications a
        on a.id = ca.application_id

      left join public.holiday_work_records h
        on h.id = ca.holiday_work_record_id
       and h.employee_id = a.employee_id
       and h.status = 'active'

      where ca.application_id = p_application_id
        and h.id is null
    )

    and not exists (

      select 1

      from public.comp_leave_dates boundary

      where boundary.application_id = p_application_id

        and (
          select sum(d.days)
          from public.comp_leave_dates d
          where d.application_id = p_application_id
            and d.leave_date >= boundary.leave_date
        )

        >

        (
          select coalesce(sum(ca.allocated_days), 0)

          from public.comp_leave_allocations ca

          join public.holiday_work_records h
            on h.id = ca.holiday_work_record_id

          where ca.application_id = p_application_id

            and (
              h.work_date + interval '1 year'
            )::date >= boundary.leave_date
        )

    );
$$;


-- =========================================================
-- 休日出勤残数再計算
-- =========================================================

create or replace function
public.recalculate_holiday_work_record(
  p_record_id bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_record public.holiday_work_records%rowtype;
  v_used numeric;
begin

  select *
  into v_record
  from public.holiday_work_records
  where id = p_record_id
  for update;

  if not found then
    raise exception 'holiday_work_record_not_found';
  end if;

  select coalesce(sum(ca.allocated_days), 0)
  into v_used
  from public.comp_leave_allocations ca
  join public.applications a
    on a.id = ca.application_id
  where ca.holiday_work_record_id = p_record_id
    and a.status = 'approved';

  if v_used + v_record.expired_days > v_record.earned_days then
    raise exception 'insufficient_comp_leave_balance';
  end if;

  update public.holiday_work_records
  set
    used_days = v_used,
    remaining_days =
      earned_days - v_used - expired_days,
    updated_by_employee_id =
      public.current_employee_id()
  where id = p_record_id;

end;
$$;


-- =========================================================
-- 失効実行RPC
-- =========================================================

create or replace function
public.expire_comp_leave_records()
returns table(
  holiday_work_record_id bigint,
  newly_expired_days numeric,
  protected_reserved_days numeric
)
language plpgsql
security definer
set search_path = ''
set timezone = 'Asia/Tokyo'
as $$
declare
  v_id bigint;
  v_record public.holiday_work_records%rowtype;
  v_reserved numeric;
  v_expire numeric;
begin

  if public.current_employee_id() is null
     or not coalesce(public.is_leave_manager(), false)
  then
    raise exception 'leave_manager_required';
  end if;

  for v_id in

    select h.id
    from public.holiday_work_records h
    where h.status = 'active'
      and h.remaining_days > 0
      and current_date >=
        (
          (
            h.work_date + interval '1 year'
          )::date + 1
        )
    order by h.id
    for update

  loop

    perform public.recalculate_holiday_work_record(v_id);

    select *
    into v_record
    from public.holiday_work_records h
    where h.id = v_id;

    if v_record.status <> 'active'
       or v_record.remaining_days <= 0
       or current_date <
          (
            (
              v_record.work_date + interval '1 year'
            )::date + 1
          )
    then
      continue;
    end if;

    select coalesce(sum(ca.allocated_days), 0)
    into v_reserved
    from public.comp_leave_allocations ca
    join public.applications a
      on a.id = ca.application_id
    where ca.holiday_work_record_id = v_id
      and a.application_type = 'comp_leave'
      and a.status = 'submitted'
      and public.comp_leave_dates_within_expiry(a.id);

    v_expire :=
      greatest(
        v_record.remaining_days - v_reserved,
        0
      );

    if v_expire <= 0 then
      continue;
    end if;

    update public.holiday_work_records h
    set
      expired_days =
        h.expired_days + v_expire,
      remaining_days =
        h.remaining_days - v_expire,
      updated_by_employee_id =
        public.current_employee_id()
    where h.id = v_id;

    insert into public.comp_leave_expirations as ledger
    (
      holiday_work_record_id,
      employee_id,
      work_date,
      valid_until_date,
      expiration_date,
      expired_at,
      earned_days,
      used_days_at_expiration,
      expired_days,
      site_id,
      note
    )
    values
    (
      v_id,
      v_record.employee_id,
      v_record.work_date,
      (
        v_record.work_date + interval '1 year'
      )::date,
      (
        (
          v_record.work_date + interval '1 year'
        )::date + 1
      ),
      now(),
      v_record.earned_days,
      v_record.used_days,
      v_record.expired_days + v_expire,
      v_record.site_id,
      v_record.note
    )
    on conflict
      on constraint comp_leave_expirations_holiday_work_record_id_key
    do update
    set
      employee_id = excluded.employee_id,
      work_date = excluded.work_date,
      valid_until_date = excluded.valid_until_date,
      expiration_date = excluded.expiration_date,
      expired_at = excluded.expired_at,
      earned_days = excluded.earned_days,
      used_days_at_expiration = excluded.used_days_at_expiration,
      expired_days = excluded.expired_days,
      site_id = excluded.site_id,
      note = excluded.note;

    perform public.recalculate_holiday_work_record(v_id);

    holiday_work_record_id := v_id;
    newly_expired_days := v_expire;
    protected_reserved_days := v_reserved;

    return next;

  end loop;

end;
$$;


-- =========================================================
-- submit_application
-- =========================================================

create or replace function
public.submit_application(
  p_application_id bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_app public.applications%rowtype;
  v_leave_days numeric(6,2);
  v_allocated_days numeric(6,2);
  v_record_id bigint;
begin

  select *
  into v_app
  from public.applications
  where id = p_application_id
  for update;

  if not found then
    raise exception 'application_not_found';
  end if;

  if v_app.employee_id <> public.current_employee_id() then
    raise exception 'forbidden';
  end if;

  if not public.can_use_application_features() then
    raise exception 'application_features_unavailable';
  end if;

  if v_app.status <> 'draft' then
    raise exception 'application_not_draft';
  end if;

  if v_app.application_type = 'paid_leave' then

    perform public.validate_paid_leave_application(v_app.id);

  elsif v_app.application_type = 'comp_leave' then

    if not exists (
      select 1
      from public.comp_leave_application_details
      where application_id = v_app.id
    ) then
      raise exception 'comp_leave_detail_required';
    end if;

    select coalesce(sum(days),0)
    into v_leave_days
    from public.comp_leave_dates
    where application_id = v_app.id;

    if v_leave_days <= 0 then
      raise exception 'comp_leave_date_required';
    end if;

    select coalesce(sum(allocated_days), 0)
    into v_allocated_days
    from public.comp_leave_allocations
    where application_id = v_app.id;

    if v_allocated_days <> v_leave_days then
      raise exception 'comp_leave_allocation_mismatch';
    end if;

    perform h.id
    from public.holiday_work_records h
    where h.id in (
      select ca.holiday_work_record_id
      from public.comp_leave_allocations ca
      where ca.application_id = v_app.id
    )
    order by h.id
    for update;

    if exists (
      select 1
      from public.comp_leave_allocations ca
      left join public.holiday_work_records h
        on h.id = ca.holiday_work_record_id
       and h.employee_id = v_app.employee_id
       and h.status = 'active'
      where ca.application_id = v_app.id
        and h.id is null
    ) then
      raise exception 'invalid_or_cancelled_holiday_work_record';
    end if;

    for v_record_id in
      select holiday_work_record_id
      from public.comp_leave_allocations
      where application_id = v_app.id
      order by holiday_work_record_id
    loop
      perform public.recalculate_holiday_work_record(v_record_id);
    end loop;

    if exists (
      select 1
      from public.comp_leave_allocations ca
      join public.comp_leave_availability_internal(
        v_app.employee_id,
        v_app.id
      ) b
        on b.id = ca.holiday_work_record_id
      where ca.application_id = v_app.id
        and ca.allocated_days > b.available_days
    ) then
      raise exception 'insufficient_comp_leave_balance';
    end if;

    if not public.comp_leave_dates_within_expiry(v_app.id) then
      raise exception 'comp_leave_date_exceeds_expiration';
    end if;

  else

    raise exception 'unsupported_application_type';

  end if;

  update public.applications
  set
    status = 'submitted',
    submitted_at = now()
  where id = v_app.id;

  insert into public.application_status_history
  (
    application_id,
    from_status,
    to_status,
    changed_by_employee_id
  )
  values
  (
    v_app.id,
    v_app.status,
    'submitted',
    public.current_employee_id()
  );

end;
$$;


-- =========================================================
-- 管理者直接代休使用
-- =========================================================

create or replace function
public.register_admin_comp_leave_usage(
  p_employee_id bigint,
  p_usage_date date,
  p_days numeric,
  p_request_id uuid,
  p_note text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor bigint;
  v_app bigint;
  v_record record;
  v_remaining numeric;
  v_take numeric;
  v_source text;
  v_previous record;
begin

  if not public.is_leave_manager() then
    raise exception '残数管理権限が必要です';
  end if;

  if p_usage_date is null
     or p_request_id is null
     or p_days is null
     or p_days <= 0
     or p_days::text in ('NaN','Infinity','-Infinity')
     or p_days <> round(p_days,2)
     or p_days > 9999.99
  then
    raise exception '使用日と0より大きい使用日数（小数2桁まで）を入力してください';
  end if;

  if not exists (
    select 1
    from public.employees
    where id = p_employee_id
      and active = true
  ) then
    raise exception '有効な対象社員を選択してください';
  end if;

  v_actor := public.current_employee_id();

  v_source :=
    'admin_comp_usage:' || p_request_id::text;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      v_source,
      0
    )
  );

  select
    a.id,
    a.employee_id,
    a.applicant_note,
    d.leave_date,
    d.days
  into v_previous
  from public.applications a
  join public.comp_leave_dates d
    on d.application_id = a.id
  where a.reviewer_comment = v_source
    and d.admin_direct;

  if found then

    if v_previous.employee_id is distinct from p_employee_id
       or v_previous.leave_date is distinct from p_usage_date
       or v_previous.days is distinct from p_days
       or v_previous.applicant_note
          is distinct from nullif(trim(p_note),'')
    then
      raise exception '同じ登録要求の内容が変更されています';
    end if;

    return v_previous.id;

  end if;

  for v_record in
    select id
    from public.holiday_work_records
    where employee_id = p_employee_id
      and status = 'active'
    order by id
    for update
  loop
    perform public.recalculate_holiday_work_record(v_record.id);
  end loop;

  select coalesce(sum(available_days), 0)
  into v_remaining
  from public.comp_leave_availability_internal(
    p_employee_id
  )
  where p_usage_date <=
    (
      work_date + interval '1 year'
    )::date;

  if p_days > v_remaining then
    raise exception '現在の代休残日数を超えています';
  end if;

  insert into public.applications
  (
    application_type,
    employee_id,
    status,
    approved_at,
    approved_by_employee_id,
    reviewer_comment,
    applicant_note,
    created_by_employee_id
  )
  values
  (
    'comp_leave',
    p_employee_id,
    'approved',
    now(),
    v_actor,
    v_source,
    nullif(trim(p_note),''),
    v_actor
  )
  returning id into v_app;

  update public.applications
  set employee_id = p_employee_id
  where id = v_app;

  insert into public.comp_leave_application_details
  (
    application_id,
    note
  )
  values
  (
    v_app,
    nullif(trim(p_note),'')
  );

  insert into public.comp_leave_dates
  (
    application_id,
    leave_date,
    days,
    admin_direct
  )
  values
  (
    v_app,
    p_usage_date,
    p_days,
    true
  );

  v_remaining := p_days;

  for v_record in
    select
      id,
      available_days
    from public.comp_leave_availability_internal(
      p_employee_id
    )
    where available_days > 0
      and p_usage_date <=
        (
          work_date + interval '1 year'
        )::date
    order by
      work_date,
      id
  loop

    exit when v_remaining = 0;

    v_take :=
      least(
        v_remaining,
        v_record.available_days
      );

    insert into public.comp_leave_allocations
    (
      application_id,
      holiday_work_record_id,
      allocated_days
    )
    values
    (
      v_app,
      v_record.id,
      v_take
    );

    perform public.recalculate_holiday_work_record(v_record.id);

    v_remaining :=
      v_remaining - v_take;

  end loop;

  if v_remaining <> 0 then
    raise exception '代休の割当残数が不足しています';
  end if;

  insert into public.application_status_history
  (
    application_id,
    from_status,
    to_status,
    comment,
    changed_by_employee_id
  )
  values
  (
    v_app,
    null,
    'approved',
    '管理者直接登録',
    v_actor
  );

  return v_app;

end;
$$;


-- =========================================================
-- review_application
-- =========================================================

create or replace function
public.review_application(
  p_application_id bigint,
  p_decision text,
  p_comment text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_app public.applications%rowtype;
  v_admin bigint;
  v_detail public.paid_leave_application_details%rowtype;
  v_fiscal_year integer;
  v_balance_id bigint;
  v_record_id bigint;
  v_leave_days numeric(6,2);
  v_allocated_days numeric(6,2);
begin

  if not public.is_application_admin() then
    raise exception 'admin_required';
  end if;

  if p_decision not in (
    'approved',
    'rejected',
    'revision_required'
  ) then
    raise exception 'invalid_decision';
  end if;

  v_admin := public.current_employee_id();

  select *
  into v_app
  from public.applications
  where id = p_application_id
  for update;

  if not found then
    raise exception 'application_not_found';
  end if;

  if v_app.status <> 'submitted' then
    raise exception 'application_not_submitted';
  end if;

  if p_decision = 'approved'
     and v_app.application_type = 'paid_leave'
  then

    perform public.validate_paid_leave_application(v_app.id);

    select *
    into v_detail
    from public.paid_leave_application_details
    where application_id = v_app.id;

    if not found then
      raise exception 'paid_leave_detail_required';
    end if;

    v_fiscal_year :=
      extract(year from v_detail.start_date)::integer
      -
      case
        when extract(month from v_detail.start_date) < 4
        then 1
        else 0
      end;

    select id
    into v_balance_id
    from public.paid_leave_balances
    where employee_id = v_app.employee_id
      and fiscal_year = v_fiscal_year
    for update;

    if not found then
      raise exception 'paid_leave_balance_not_found';
    end if;

    if exists (
      select 1
      from public.paid_leave_balances b
      where b.id = v_balance_id
        and b.base_date is not null
        and v_detail.start_date <= b.base_date
    ) then
      raise exception 'paid_leave_date_already_in_imported_period';
    end if;

    insert into public.paid_leave_balance_transactions
    (
      balance_id,
      application_id,
      transaction_type,
      days,
      source_key,
      created_by_employee_id
    )
    values
    (
      v_balance_id,
      v_app.id,
      'application_usage',
      -v_detail.days,
      'application:' || v_app.id::text,
      v_admin
    )
    on conflict (
      balance_id,
      source_key
    )
    do update
    set
      days = excluded.days,
      active = true;

  end if;

  if p_decision = 'approved'
     and v_app.application_type = 'comp_leave'
  then

    select coalesce(sum(days),0)
    into v_leave_days
    from public.comp_leave_dates
    where application_id = v_app.id;

    select coalesce(sum(allocated_days),0)
    into v_allocated_days
    from public.comp_leave_allocations
    where application_id = v_app.id;

    if v_leave_days <= 0 then
      raise exception 'comp_leave_date_required';
    end if;

    if v_leave_days <> v_allocated_days then
      raise exception 'comp_leave_allocation_mismatch';
    end if;

    if exists (
      select 1
      from public.comp_leave_allocations ca
      left join public.holiday_work_records h
        on h.id = ca.holiday_work_record_id
       and h.employee_id = v_app.employee_id
       and h.status = 'active'
      where ca.application_id = v_app.id
        and h.id is null
    ) then
      raise exception 'invalid_or_cancelled_holiday_work_record';
    end if;

    for v_record_id in
      select h.id
      from public.holiday_work_records h
      join public.comp_leave_allocations ca
        on ca.holiday_work_record_id = h.id
      where ca.application_id = v_app.id
        and h.employee_id = v_app.employee_id
        and h.status = 'active'
      order by h.id
      for update of h
    loop
      null;
    end loop;

    if not exists (
      select 1
      from public.comp_leave_allocations
      where application_id = v_app.id
    ) then
      raise exception 'comp_leave_allocation_required';
    end if;

    if not public.comp_leave_dates_within_expiry(v_app.id) then
      raise exception 'comp_leave_date_exceeds_expiration';
    end if;

  end if;

  update public.applications
  set
    status = p_decision,
    reviewer_comment = nullif(trim(p_comment),''),
    approved_at =
      case
        when p_decision = 'approved'
        then now()
        else null
      end,
    approved_by_employee_id =
      case
        when p_decision = 'approved'
        then v_admin
        else null
      end,
    rejected_at =
      case
        when p_decision = 'rejected'
        then now()
        else null
      end,
    rejected_by_employee_id =
      case
        when p_decision = 'rejected'
        then v_admin
        else null
      end
  where id = v_app.id;

  if p_decision = 'approved'
     and v_app.application_type = 'paid_leave'
  then

    perform public.recalculate_paid_leave_balance(v_balance_id);

  elsif p_decision = 'approved'
        and v_app.application_type = 'comp_leave'
  then

    for v_record_id in
      select holiday_work_record_id
      from public.comp_leave_allocations
      where application_id = v_app.id
      order by holiday_work_record_id
    loop
      perform public.recalculate_holiday_work_record(v_record_id);
    end loop;

  end if;

  insert into public.application_status_history
  (
    application_id,
    from_status,
    to_status,
    comment,
    changed_by_employee_id
  )
  values
  (
    v_app.id,
    v_app.status,
    p_decision,
    nullif(trim(p_comment),''),
    v_admin
  );

end;
$$;


-- =========================================================
-- 休日出勤訂正
-- =========================================================

create or replace function
public.update_holiday_work(
  p_record_id bigint,
  p_work_date date,
  p_earned_days numeric,
  p_site_id bigint default null,
  p_note text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_record public.holiday_work_records%rowtype;
  v_approved_used numeric(6,2);
  v_committed_allocated numeric(6,2);
begin

  if not public.is_leave_manager() then
    raise exception 'leave_manager_required';
  end if;

  if p_earned_days <= 0 then
    raise exception 'invalid_earned_days';
  end if;

  select *
  into v_record
  from public.holiday_work_records
  where id = p_record_id
  for update;

  if not found then
    raise exception 'holiday_work_record_not_found';
  end if;

  if v_record.status = 'cancelled' then
    raise exception 'holiday_work_record_already_cancelled';
  end if;

  select
    coalesce(
      sum(ca.allocated_days)
      filter (
        where a.status = 'approved'
      ),
      0
    ),
    coalesce(
      sum(ca.allocated_days)
      filter (
        where a.status in (
          'submitted',
          'approved'
        )
      ),
      0
    )
  into
    v_approved_used,
    v_committed_allocated
  from public.comp_leave_allocations ca
  join public.applications a
    on a.id = ca.application_id
  where ca.holiday_work_record_id = p_record_id;

  if p_earned_days <
     v_committed_allocated + v_record.expired_days
  then
    raise exception
      'earned_days_cannot_be_less_than_submitted_or_approved_comp_leave_allocation';
  end if;

  update public.holiday_work_records
  set
    work_date = p_work_date,
    earned_days = p_earned_days,
    used_days = v_approved_used,
    remaining_days =
      p_earned_days
      - v_approved_used
      - expired_days,
    site_id = p_site_id,
    note = nullif(trim(p_note),''),
    updated_by_employee_id =
      public.current_employee_id()
  where id = p_record_id;

end;
$$;


-- =========================================================
-- 休日出勤取消
-- =========================================================

create or replace function
public.cancel_holiday_work(
  p_record_id bigint,
  p_comment text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_record public.holiday_work_records%rowtype;
  v_committed_allocated numeric(6,2);
begin

  if not public.is_leave_manager() then
    raise exception 'leave_manager_required';
  end if;

  select *
  into v_record
  from public.holiday_work_records
  where id = p_record_id
  for update;

  if not found then
    raise exception 'holiday_work_record_not_found';
  end if;

  if v_record.status = 'cancelled' then
    return;
  end if;

  select coalesce(sum(ca.allocated_days), 0)
  into v_committed_allocated
  from public.comp_leave_allocations ca
  join public.applications a
    on a.id = ca.application_id
  where ca.holiday_work_record_id = p_record_id
    and a.status in (
      'submitted',
      'approved'
    );

  if v_committed_allocated > 0 then
    raise exception
      'holiday_work_allocated_to_submitted_or_approved_application_cannot_cancel';
  end if;

  update public.holiday_work_records
  set
    status = 'cancelled',
    used_days = 0,
    remaining_days =
      earned_days - expired_days,
    note =
      case
        when nullif(trim(p_comment),'') is null
        then note
        else concat_ws(
          E'\n',
          note,
          '取消理由: ' || trim(p_comment)
        )
      end,
    updated_by_employee_id =
      public.current_employee_id()
  where id = p_record_id;

end;
$$;


-- =========================================================
-- 権限
-- =========================================================

revoke all
on function
public.comp_leave_dates_within_expiry(bigint)
from public, anon, authenticated;

revoke all
on function
public.recalculate_holiday_work_record(bigint)
from public, anon, authenticated;

revoke all
on function
public.expire_comp_leave_records()
from public, anon, authenticated;

grant execute
on function
public.expire_comp_leave_records()
to authenticated;

revoke all
on function
public.submit_application(bigint)
from public, anon;

revoke all
on function
public.review_application(bigint,text,text)
from public, anon;

revoke all
on function
public.register_admin_comp_leave_usage(
  bigint,
  date,
  numeric,
  uuid,
  text
)
from public, anon;

revoke all
on function
public.update_holiday_work(
  bigint,
  date,
  numeric,
  bigint,
  text
)
from public, anon;

revoke all
on function
public.cancel_holiday_work(
  bigint,
  text
)
from public, anon;

grant execute
on function
public.submit_application(bigint)
to authenticated;

grant execute
on function
public.review_application(
  bigint,
  text,
  text
)
to authenticated;

grant execute
on function
public.register_admin_comp_leave_usage(
  bigint,
  date,
  numeric,
  uuid,
  text
)
to authenticated;

grant execute
on function
public.update_holiday_work(
  bigint,
  date,
  numeric,
  bigint,
  text
)
to authenticated;

grant execute
on function
public.cancel_holiday_work(
  bigint,
  text
)
to authenticated;

notify pgrst, 'reload schema';

commit;