-- Prerequisites:
-- personal_tool_registration.sql
-- add_personal_tool_registration_details.sql
-- add_personal_tool_update.sql
-- add_personal_tool_identity_correction.sql
--
-- Run tool_catalog_preflight.sql first.
-- This transaction never rewrites existing tools.

begin;


/* =========================================
   tool_catalog
========================================= */

create table if not exists public.tool_catalog (
  id bigint generated by default as identity primary key,

  tool_group text not null
    check (
      tool_group <> ''
      and tool_group = btrim(tool_group)
    ),

  tool_name text not null
    check (
      tool_name <> ''
      and tool_name = btrim(tool_name)
    ),

  code_prefix text not null
    check (
      code_prefix ~
      '^[A-Za-z0-9]+(-[A-Za-z0-9]+)*$'
    ),

  inspection_required boolean
    not null
    default true,

  inspection_category text null
    check (
      inspection_category in (
        '3p',
        'double_insulated',
        'battery',
        'cord_reel',
        'ac_welder',
        'dc_welder'
      )
    ),

  active boolean
    not null
    default true,

  sort_order integer
    not null
    default 0,

  created_at timestamptz
    not null
    default now(),

  updated_at timestamptz
    not null
    default now(),

  unique (
    tool_group,
    tool_name
  )
);


/* =========================================
   旧ドラフト制約除去
========================================= */

alter table public.tool_catalog
  drop constraint
  if exists tool_catalog_check;


/* =========================================
   RLS
========================================= */

alter table public.tool_catalog
  enable row level security;


revoke all
on public.tool_catalog
from public, anon, authenticated;


grant
  select,
  insert,
  update
on public.tool_catalog
to authenticated;


grant
  usage,
  select
on sequence public.tool_catalog_id_seq
to authenticated;


/* =========================================
   SELECT
========================================= */

drop policy
if exists tool_catalog_read
on public.tool_catalog;


create policy tool_catalog_read
on public.tool_catalog
for select
to authenticated
using (true);


/* =========================================
   INSERT
========================================= */

drop policy
if exists tool_catalog_insert
on public.tool_catalog;


create policy tool_catalog_insert
on public.tool_catalog
for insert
to authenticated
with check (
  public.is_tool_registration_admin()
);


/* =========================================
   UPDATE
========================================= */

drop policy
if exists tool_catalog_update
on public.tool_catalog;


create policy tool_catalog_update
on public.tool_catalog
for update
to authenticated
using (
  public.is_tool_registration_admin()
)
with check (
  public.is_tool_registration_admin()
);


/* =========================================
   updated_at
========================================= */

create or replace function
public.touch_tool_catalog()
returns trigger
language plpgsql
set search_path = ''
as $$
begin

  new.updated_at := now();

  return new;

end;
$$;


revoke all
on function public.touch_tool_catalog()
from public, anon, authenticated;


drop trigger
if exists tool_catalog_updated
on public.tool_catalog;


create trigger tool_catalog_updated
before update
on public.tool_catalog
for each row
execute function public.touch_tool_catalog();


/* =========================================
   既存 tools をスナップショットとして参照
   ※既存 tools は変更しない
========================================= */

lock table public.tools
in share mode;


/* =========================================
   手動確認対象一覧
========================================= */

with normalized as (

  select
    t.*,

    case inspection_category

      when '3P'
        then '3p'

      when '二重絶縁'
        then 'double_insulated'

      else inspection_category

    end as normalized_category,

    case

      when management_code ~ '^.+-[0-9]+$'
        then regexp_replace(
          management_code,
          '-[0-9]+$',
          ''
        )

    end as parsed_prefix

  from public.tools t

),

grouped as (

  select
    tool_group,
    tool_name,

    count(*) as tool_count,

    array_agg(
      distinct management_code
      order by management_code
    ) as management_codes,

    array_agg(
      distinct parsed_prefix
    ) as prefixes,

    array_agg(
      distinct inspection_required
    ) as required_values,

    array_agg(
      distinct inspection_category
    ) as original_categories,

    array_agg(
      distinct normalized_category
    ) as category_values,

    bool_and(
      coalesce(
        management_code ~
        '^[A-Za-z0-9]+(-[A-Za-z0-9]+)*-[0-9]+$',
        false
      )
    ) as valid_codes,

    bool_and(
      coalesce(
        management_code ~
        '^SB-(1IN|2IN|3IN|4IN)-[0-9]+$',
        false
      )
    ) as lathe_size_codes

  from normalized

  group by
    tool_group,
    tool_name

),

reviewed as (

  select
    g.*,

    case

      when
        tool_name = '旋盤'
        and lathe_size_codes
      then 'SB'

      else prefixes[1]

    end as proposed_prefix,

    array_remove(
      array[

        case
          when
            tool_group is null
            or btrim(tool_group) = ''
            or tool_group <> btrim(tool_group)
            or tool_name is null
            or btrim(tool_name) = ''
            or tool_name <> btrim(tool_name)
          then
            '大分類・工具名が空または前後空白あり'
        end,

        case
          when not valid_codes
          then
            '管理番号が未設定または未対応形式'
        end,

        case
          when
            tool_name = '旋盤'
            and not lathe_size_codes
          then
            '旋盤の想定外接頭辞（SB-1IN〜SB-4IN以外）'
        end,

        case
          when
            tool_name is distinct from '旋盤'
            and cardinality(prefixes) <> 1
          then
            '管理番号接頭辞が複数'
        end,

        case
          when
            cardinality(required_values) <> 1
            or required_values[1] is null
          then
            '点検対象が混在またはNULL'
        end,

        case
          when
            cardinality(category_values) <> 1
          then
            '正規化後の点検区分が混在'
        end,

        case
          when
            '要確認' = any(category_values)
          then
            '点検区分が要確認'
        end,

        case
          when exists (
            select 1

            from unnest(
              category_values
            ) category

            where
              category is not null
              and category not in (
                '3p',
                'double_insulated',
                'battery',
                'cord_reel',
                'ac_welder',
                'dc_welder',
                '要確認'
              )
          )
          then
            '未対応の点検区分'
        end

      ]::text[],
      null
    ) as review_reasons

  from grouped g

),

seed as (

  select
    *,

    cardinality(
      review_reasons
    ) = 0 as auto_migrate

  from reviewed

)

select
  tool_group,
  tool_name,
  tool_count,
  management_codes,
  prefixes,
  required_values,
  original_categories,
  category_values,
  review_reasons

from seed

where not auto_migrate

order by
  tool_group,
  tool_name;


/* =========================================
   安全に移行できる工具名だけ登録
========================================= */

with normalized as (

  select
    t.*,

    case inspection_category

      when '3P'
        then '3p'

      when '二重絶縁'
        then 'double_insulated'

      else inspection_category

    end as normalized_category,

    case

      when management_code ~ '^.+-[0-9]+$'
        then regexp_replace(
          management_code,
          '-[0-9]+$',
          ''
        )

    end as parsed_prefix

  from public.tools t

),

grouped as (

  select
    tool_group,
    tool_name,

    count(*) as tool_count,

    array_agg(
      distinct management_code
      order by management_code
    ) as management_codes,

    array_agg(
      distinct parsed_prefix
    ) as prefixes,

    array_agg(
      distinct inspection_required
    ) as required_values,

    array_agg(
      distinct inspection_category
    ) as original_categories,

    array_agg(
      distinct normalized_category
    ) as category_values,

    bool_and(
      coalesce(
        management_code ~
        '^[A-Za-z0-9]+(-[A-Za-z0-9]+)*-[0-9]+$',
        false
      )
    ) as valid_codes,

    bool_and(
      coalesce(
        management_code ~
        '^SB-(1IN|2IN|3IN|4IN)-[0-9]+$',
        false
      )
    ) as lathe_size_codes

  from normalized

  group by
    tool_group,
    tool_name

),

reviewed as (

  select
    g.*,

    case

      when
        tool_name = '旋盤'
        and lathe_size_codes
      then 'SB'

      else prefixes[1]

    end as proposed_prefix,

    array_remove(
      array[

        case
          when
            tool_group is null
            or btrim(tool_group) = ''
            or tool_group <> btrim(tool_group)
            or tool_name is null
            or btrim(tool_name) = ''
            or tool_name <> btrim(tool_name)
          then
            '大分類・工具名が空または前後空白あり'
        end,

        case
          when not valid_codes
          then
            '管理番号が未設定または未対応形式'
        end,

        case
          when
            tool_name = '旋盤'
            and not lathe_size_codes
          then
            '旋盤の想定外接頭辞（SB-1IN〜SB-4IN以外）'
        end,

        case
          when
            tool_name is distinct from '旋盤'
            and cardinality(prefixes) <> 1
          then
            '管理番号接頭辞が複数'
        end,

        case
          when
            cardinality(required_values) <> 1
            or required_values[1] is null
          then
            '点検対象が混在またはNULL'
        end,

        case
          when
            cardinality(category_values) <> 1
          then
            '正規化後の点検区分が混在'
        end,

        case
          when
            '要確認' = any(category_values)
          then
            '点検区分が要確認'
        end,

        case
          when exists (
            select 1

            from unnest(
              category_values
            ) category

            where
              category is not null
              and category not in (
                '3p',
                'double_insulated',
                'battery',
                'cord_reel',
                'ac_welder',
                'dc_welder',
                '要確認'
              )
          )
          then
            '未対応の点検区分'
        end

      ]::text[],
      null
    ) as review_reasons

  from grouped g

),

seed as (

  select
    *,

    cardinality(
      review_reasons
    ) = 0 as auto_migrate

  from reviewed

)

insert into public.tool_catalog (
  tool_group,
  tool_name,
  code_prefix,
  inspection_required,
  inspection_category
)

select
  tool_group,
  tool_name,
  proposed_prefix,
  required_values[1],
  category_values[1]

from seed

where auto_migrate

on conflict (
  tool_group,
  tool_name
)
do nothing;


/* =========================================
   PostgREST
========================================= */

notify pgrst, 'reload schema';


commit;