-- ============================================================================
-- Staff Portal 各種申請基盤
-- IMPORTANT: レビュー用SQLです。確認完了前に本番環境へ実行しないでください。
-- 前提: public.employees(id bigint, auth_user_id uuid, active boolean,
--       admin_scope text), public.sites(id bigint), public.attendance(id bigint)
-- ============================================================================

begin;

-- --------------------------------------------------------------------------
-- 1. テーブル
-- --------------------------------------------------------------------------

create table if not exists public.application_types (
  code text primary key,
  display_name text not null,
  category text not null,
  detail_kind text not null unique,
  active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (code ~ '^[a-z][a-z0-9_]*$')
);

insert into public.application_types
  (code, display_name, category, detail_kind, display_order)
values
  ('paid_leave', '有給休暇申請', 'leave', 'paid_leave', 10),
  ('comp_leave', '代替休日申請', 'leave', 'comp_leave', 20)
on conflict (code) do update set
  display_name = excluded.display_name,
  category = excluded.category,
  detail_kind = excluded.detail_kind,
  display_order = excluded.display_order;

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  application_type text not null references public.application_types(code),
  employee_id bigint not null references public.employees(id),
  status text not null default 'draft'
    check (status in (
      'draft', 'submitted', 'approved', 'rejected',
      'revision_required', 'cancelled'
    )),
  submitted_at timestamptz,
  approved_at timestamptz,
  approved_by_employee_id bigint references public.employees(id),
  rejected_at timestamptz,
  rejected_by_employee_id bigint references public.employees(id),
  reviewer_comment text,
  applicant_note text,
  created_by_employee_id bigint not null references public.employees(id),
  updated_by_employee_id bigint references public.employees(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    status <> 'approved'
    or (approved_at is not null and approved_by_employee_id is not null)
  ),
  check (
    status <> 'rejected'
    or (rejected_at is not null and rejected_by_employee_id is not null)
  )
);

create table if not exists public.application_status_history (
  id bigint generated by default as identity primary key,
  application_id bigint not null
    references public.applications(id) on delete cascade,
  from_status text,
  to_status text not null,
  comment text,
  changed_by_employee_id bigint not null references public.employees(id),
  changed_at timestamptz not null default now()
);

create table if not exists public.paid_leave_application_details (
  application_id bigint primary key
    references public.applications(id) on delete cascade,
  site_id bigint references public.sites(id) on delete set null,
  start_date date not null,
  end_date date not null,
  days numeric(6,2) not null,
  day_part text not null default 'full'
    check (day_part in ('full', 'am', 'pm', 'custom')),
  reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint paid_leave_date_order_check check (end_date >= start_date),
  constraint paid_leave_same_fiscal_year_check check (
    extract(year from start_date)::integer
      - case when extract(month from start_date) < 4 then 1 else 0 end
    =
    extract(year from end_date)::integer
      - case when extract(month from end_date) < 4 then 1 else 0 end
  ),
  constraint paid_leave_days_positive_check check (days > 0),
  constraint paid_leave_day_part_days_check check (
    (day_part in ('am', 'pm') and start_date = end_date and days = 0.5)
    or (day_part = 'full' and days >= 1 and days <= (end_date - start_date + 1))
    or (day_part = 'custom' and days <= (end_date - start_date + 1))
  )
);

create table if not exists public.comp_leave_application_details (
  application_id bigint primary key
    references public.applications(id) on delete cascade,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.comp_leave_dates (
  id bigint generated by default as identity primary key,
  application_id bigint not null
    references public.comp_leave_application_details(application_id)
    on delete cascade,
  leave_date date not null,
  days numeric(6,2) not null
    check (days in (0.5, 1.0)),
  display_order integer not null default 0 check (display_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (application_id, leave_date)
);

create table if not exists public.paid_leave_balances (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id),
  fiscal_year integer not null check (fiscal_year between 2000 and 2200),
  granted_days numeric(7,2) not null default 0 check (granted_days >= 0),
  carried_days numeric(7,2) not null default 0 check (carried_days >= 0),
  imported_used_days numeric(7,2) not null default 0 check (imported_used_days >= 0),
  adjustment_days numeric(7,2) not null default 0,
  used_days numeric(7,2) not null default 0 check (used_days >= 0),
  remaining_days numeric(7,2) not null default 0,
  base_date date,
  created_by_employee_id bigint references public.employees(id),
  updated_by_employee_id bigint references public.employees(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (employee_id, fiscal_year)
);

create table if not exists public.paid_leave_balance_transactions (
  id bigint generated by default as identity primary key,
  balance_id bigint not null
    references public.paid_leave_balances(id) on delete cascade,
  application_id bigint references public.applications(id),
  transaction_type text not null
    check (transaction_type in (
      'grant', 'carryover', 'imported_usage',
      'application_usage', 'adjustment'
    )),
  days numeric(7,2) not null,
  source_key text not null,
  active boolean not null default true,
  reason text,
  created_by_employee_id bigint references public.employees(id),
  created_at timestamptz not null default now(),
  unique (balance_id, source_key),
  check (
    (transaction_type in ('grant', 'carryover') and days >= 0)
    or (transaction_type in ('imported_usage', 'application_usage') and days <= 0)
    or transaction_type = 'adjustment'
  )
);

create unique index if not exists paid_leave_application_usage_uidx
  on public.paid_leave_balance_transactions (application_id)
  where transaction_type = 'application_usage';

create table if not exists public.holiday_work_records (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id),
  work_date date not null,
  earned_days numeric(6,2) not null check (earned_days > 0),
  used_days numeric(6,2) not null default 0 check (used_days >= 0),
  remaining_days numeric(6,2) not null check (remaining_days >= 0),
  site_id bigint references public.sites(id) on delete set null,
  note text,
  status text not null default 'active'
    check (status in ('active', 'cancelled')),
  source_type text not null default 'manual'
    check (source_type in ('manual', 'attendance', 'import')),
  source_attendance_id bigint
    references public.attendance(id) on delete set null,
  created_by_employee_id bigint not null references public.employees(id),
  updated_by_employee_id bigint references public.employees(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (used_days <= earned_days),
  check (remaining_days = earned_days - used_days)
);

create unique index if not exists holiday_work_attendance_source_uidx
  on public.holiday_work_records (source_attendance_id)
  where source_attendance_id is not null and status = 'active';

create table if not exists public.comp_leave_allocations (
  id bigint generated by default as identity primary key,
  application_id bigint not null
    references public.comp_leave_application_details(application_id)
    on delete cascade,
  holiday_work_record_id bigint not null
    references public.holiday_work_records(id),
  allocated_days numeric(6,2) not null check (allocated_days > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (application_id, holiday_work_record_id)
);

-- --------------------------------------------------------------------------
-- 2. 補助関数・updated_at
-- --------------------------------------------------------------------------

create or replace function public.current_employee_id()
returns bigint
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select e.id
  from public.employees e
  where e.auth_user_id = auth.uid()
    and e.active = true
  limit 1
$$;

create or replace function public.is_application_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.employees e
    where e.auth_user_id = auth.uid()
      and e.active = true
      and e.admin_scope = 'all'
  )
$$;

create or replace function public.set_application_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.set_application_actor()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'INSERT' then
    new.created_by_employee_id := public.current_employee_id();
    new.employee_id := public.current_employee_id();
  end if;
  new.updated_by_employee_id := public.current_employee_id();
  return new;
end;
$$;

drop trigger if exists applications_updated_at on public.applications;
create trigger applications_updated_at
before update on public.applications
for each row execute function public.set_application_updated_at();

drop trigger if exists applications_actor on public.applications;
create trigger applications_actor
before insert or update on public.applications
for each row execute function public.set_application_actor();

drop trigger if exists application_types_updated_at on public.application_types;
create trigger application_types_updated_at
before update on public.application_types
for each row execute function public.set_application_updated_at();

drop trigger if exists paid_leave_details_updated_at on public.paid_leave_application_details;
create trigger paid_leave_details_updated_at
before update on public.paid_leave_application_details
for each row execute function public.set_application_updated_at();

drop trigger if exists comp_leave_details_updated_at on public.comp_leave_application_details;
create trigger comp_leave_details_updated_at
before update on public.comp_leave_application_details
for each row execute function public.set_application_updated_at();

drop trigger if exists comp_leave_dates_updated_at on public.comp_leave_dates;
create trigger comp_leave_dates_updated_at
before update on public.comp_leave_dates
for each row execute function public.set_application_updated_at();

drop trigger if exists paid_leave_balances_updated_at on public.paid_leave_balances;
create trigger paid_leave_balances_updated_at
before update on public.paid_leave_balances
for each row execute function public.set_application_updated_at();

drop trigger if exists holiday_work_records_updated_at on public.holiday_work_records;
create trigger holiday_work_records_updated_at
before update on public.holiday_work_records
for each row execute function public.set_application_updated_at();

drop trigger if exists comp_leave_allocations_updated_at on public.comp_leave_allocations;
create trigger comp_leave_allocations_updated_at
before update on public.comp_leave_allocations
for each row execute function public.set_application_updated_at();

-- --------------------------------------------------------------------------
-- 3. 再計算関数（外部から直接実行させない内部関数）
-- --------------------------------------------------------------------------

create or replace function public.recalculate_paid_leave_balance(p_balance_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_balance public.paid_leave_balances%rowtype;
  v_granted numeric(7,2);
  v_carried numeric(7,2);
  v_imported_used numeric(7,2);
  v_application_used numeric(7,2);
  v_adjustment numeric(7,2);
  v_remaining numeric(7,2);
begin
  select * into v_balance
  from public.paid_leave_balances
  where id = p_balance_id
  for update;

  if not found then raise exception 'paid_leave_balance_not_found'; end if;

  select
    coalesce(sum(days) filter (where transaction_type = 'grant' and active), 0),
    coalesce(sum(days) filter (where transaction_type = 'carryover' and active), 0),
    coalesce(-sum(days) filter (where transaction_type = 'imported_usage' and active), 0),
    coalesce(-sum(days) filter (where transaction_type = 'application_usage' and active), 0),
    coalesce(sum(days) filter (where transaction_type = 'adjustment' and active), 0),
    coalesce(sum(days) filter (where active), 0)
  into v_granted, v_carried, v_imported_used,
       v_application_used, v_adjustment, v_remaining
  from public.paid_leave_balance_transactions
  where balance_id = p_balance_id;

  if v_remaining < 0 then raise exception 'insufficient_paid_leave_balance'; end if;

  update public.paid_leave_balances
  set granted_days = v_granted,
      carried_days = v_carried,
      imported_used_days = v_imported_used,
      adjustment_days = v_adjustment,
      used_days = v_imported_used + v_application_used,
      remaining_days = v_remaining,
      updated_by_employee_id = public.current_employee_id()
  where id = p_balance_id;
end;
$$;

create or replace function public.recalculate_holiday_work_record(p_record_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_record public.holiday_work_records%rowtype;
  v_used numeric(6,2);
begin
  select * into v_record
  from public.holiday_work_records
  where id = p_record_id
  for update;

  if not found then raise exception 'holiday_work_record_not_found'; end if;

  select coalesce(sum(ca.allocated_days), 0)
  into v_used
  from public.comp_leave_allocations ca
  join public.applications a on a.id = ca.application_id
  where ca.holiday_work_record_id = p_record_id
    and a.status = 'approved';

  if v_used > v_record.earned_days then
    raise exception 'insufficient_comp_leave_balance';
  end if;

  update public.holiday_work_records
  set used_days = v_used,
      remaining_days = earned_days - v_used,
      updated_by_employee_id = public.current_employee_id()
  where id = p_record_id;
end;
$$;

create or replace function public.validate_paid_leave_application(p_application_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_detail public.paid_leave_application_details%rowtype;
  v_start_fiscal_year integer;
  v_end_fiscal_year integer;
  v_calendar_days integer;
begin
  select * into v_detail
  from public.paid_leave_application_details
  where application_id = p_application_id;
  if not found then raise exception 'paid_leave_detail_required'; end if;

  if v_detail.end_date < v_detail.start_date then
    raise exception 'paid_leave_end_date_before_start_date';
  end if;

  v_start_fiscal_year := extract(year from v_detail.start_date)::integer
    - case when extract(month from v_detail.start_date) < 4 then 1 else 0 end;
  v_end_fiscal_year := extract(year from v_detail.end_date)::integer
    - case when extract(month from v_detail.end_date) < 4 then 1 else 0 end;
  if v_start_fiscal_year <> v_end_fiscal_year then
    raise exception 'paid_leave_cross_fiscal_year_not_allowed';
  end if;

  v_calendar_days := v_detail.end_date - v_detail.start_date + 1;
  if v_detail.days <= 0 then raise exception 'paid_leave_days_must_be_positive'; end if;
  if v_detail.day_part in ('am', 'pm')
     and (v_detail.start_date <> v_detail.end_date or v_detail.days <> 0.5) then
    raise exception 'paid_leave_half_day_must_be_0_5';
  end if;
  if v_detail.day_part = 'full' and v_detail.days < 1 then
    raise exception 'paid_leave_full_day_must_be_at_least_1';
  end if;
  if v_detail.days > v_calendar_days then
    raise exception 'paid_leave_days_exceed_calendar_range';
  end if;
end;
$$;

-- --------------------------------------------------------------------------
-- 4. 申請状態遷移RPC
-- --------------------------------------------------------------------------

create or replace function public.submit_application(p_application_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_app public.applications%rowtype;
  v_leave_days numeric(6,2);
  v_allocated_days numeric(6,2);
begin
  select * into v_app from public.applications
  where id = p_application_id for update;

  if not found then raise exception 'application_not_found'; end if;
  if v_app.employee_id <> public.current_employee_id() then raise exception 'forbidden'; end if;
  if v_app.status <> 'draft' then raise exception 'application_not_draft'; end if;

  if v_app.application_type = 'paid_leave' then
    perform public.validate_paid_leave_application(v_app.id);
  elsif v_app.application_type = 'comp_leave' then
    if not exists (select 1 from public.comp_leave_application_details
      where application_id = v_app.id) then
      raise exception 'comp_leave_detail_required';
    end if;
    select coalesce(sum(days), 0) into v_leave_days
    from public.comp_leave_dates where application_id = v_app.id;
    if v_leave_days <= 0 then raise exception 'comp_leave_date_required'; end if;
    select coalesce(sum(allocated_days), 0) into v_allocated_days
    from public.comp_leave_allocations where application_id = v_app.id;
    if v_allocated_days <> v_leave_days then
      raise exception 'comp_leave_allocation_mismatch';
    end if;
  else
    raise exception 'unsupported_application_type';
  end if;

  update public.applications
  set status = 'submitted', submitted_at = now()
  where id = v_app.id;

  insert into public.application_status_history
    (application_id, from_status, to_status, changed_by_employee_id)
  values (v_app.id, v_app.status, 'submitted', public.current_employee_id());
end;
$$;

create or replace function public.reopen_application_draft(p_application_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_app public.applications%rowtype;
begin
  select * into v_app from public.applications
  where id = p_application_id for update;
  if not found then raise exception 'application_not_found'; end if;
  if v_app.employee_id <> public.current_employee_id() then raise exception 'forbidden'; end if;
  if v_app.status <> 'revision_required' then raise exception 'application_not_revision_required'; end if;

  update public.applications set status = 'draft' where id = v_app.id;
  insert into public.application_status_history
    (application_id, from_status, to_status, changed_by_employee_id)
  values (v_app.id, v_app.status, 'draft', public.current_employee_id());
end;
$$;

create or replace function public.delete_draft_application(p_application_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_app public.applications%rowtype;
  v_actor bigint;
begin
  v_actor := public.current_employee_id();
  if v_actor is null then raise exception 'employee_not_found'; end if;

  select * into v_app
  from public.applications
  where id = p_application_id
  for update;

  if not found then raise exception 'application_not_found'; end if;
  if v_app.employee_id <> v_actor then
    raise exception 'draft_application_owner_required';
  end if;
  if v_app.status <> 'draft' then raise exception 'application_not_draft'; end if;

  -- 詳細・代休日・割当・状態履歴は既存FKのON DELETE CASCADEで削除します。
  delete from public.applications where id = v_app.id;
end;
$$;

create or replace function public.review_application(
  p_application_id bigint,
  p_decision text,
  p_comment text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_app public.applications%rowtype;
  v_admin bigint;
  v_detail public.paid_leave_application_details%rowtype;
  v_fiscal_year integer;
  v_balance_id bigint;
  v_record_id bigint;
  v_leave_days numeric(6,2);
  v_allocated_days numeric(6,2);
begin
  if not public.is_application_admin() then raise exception 'admin_required'; end if;
  if p_decision not in ('approved', 'rejected', 'revision_required') then
    raise exception 'invalid_decision';
  end if;

  v_admin := public.current_employee_id();
  select * into v_app from public.applications
  where id = p_application_id for update;
  if not found then raise exception 'application_not_found'; end if;
  if v_app.status <> 'submitted' then raise exception 'application_not_submitted'; end if;

  if p_decision = 'approved' and v_app.application_type = 'paid_leave' then
    perform public.validate_paid_leave_application(v_app.id);
    select * into v_detail from public.paid_leave_application_details
    where application_id = v_app.id;
    if not found then raise exception 'paid_leave_detail_required'; end if;

    v_fiscal_year := extract(year from v_detail.start_date)::integer
      - case when extract(month from v_detail.start_date) < 4 then 1 else 0 end;

    select id into v_balance_id from public.paid_leave_balances
    where employee_id = v_app.employee_id and fiscal_year = v_fiscal_year
    for update;
    if not found then raise exception 'paid_leave_balance_not_found'; end if;

    -- base_date以前（同日を含む）の使用実績は経理取込済み使用日数に
    -- 含まれるため、Staff Portal側で再承認して二重計上させません。
    if exists (
      select 1
      from public.paid_leave_balances b
      where b.id = v_balance_id
        and b.base_date is not null
        and v_detail.start_date <= b.base_date
    ) then
      raise exception 'paid_leave_date_already_in_imported_period';
    end if;

    insert into public.paid_leave_balance_transactions
      (balance_id, application_id, transaction_type, days, source_key,
       created_by_employee_id)
    values
      (v_balance_id, v_app.id, 'application_usage', -v_detail.days,
       'application:' || v_app.id::text, v_admin)
    on conflict (balance_id, source_key) do update
      set days = excluded.days, active = true;
  end if;

  if p_decision = 'approved' and v_app.application_type = 'comp_leave' then
    select coalesce(sum(days), 0) into v_leave_days
    from public.comp_leave_dates where application_id = v_app.id;
    select coalesce(sum(allocated_days), 0) into v_allocated_days
    from public.comp_leave_allocations where application_id = v_app.id;
    if v_leave_days <= 0 then raise exception 'comp_leave_date_required'; end if;
    if v_leave_days <> v_allocated_days then raise exception 'comp_leave_allocation_mismatch'; end if;
    if exists (
      select 1
      from public.comp_leave_allocations ca
      left join public.holiday_work_records h
        on h.id = ca.holiday_work_record_id
       and h.employee_id = v_app.employee_id
       and h.status = 'active'
      where ca.application_id = v_app.id and h.id is null
    ) then raise exception 'invalid_or_cancelled_holiday_work_record'; end if;
    -- デッドロック防止のためID順でロックします。
    for v_record_id in
      select h.id
      from public.holiday_work_records h
      join public.comp_leave_allocations ca on ca.holiday_work_record_id = h.id
      where ca.application_id = v_app.id
        and h.employee_id = v_app.employee_id
        and h.status = 'active'
      order by h.id
      for update of h
    loop
      null;
    end loop;
    if not exists (select 1 from public.comp_leave_allocations where application_id = v_app.id)
    then raise exception 'comp_leave_allocation_required'; end if;
  end if;

  update public.applications
  set status = p_decision,
      reviewer_comment = nullif(trim(p_comment), ''),
      approved_at = case when p_decision = 'approved' then now() else null end,
      approved_by_employee_id = case when p_decision = 'approved' then v_admin else null end,
      rejected_at = case when p_decision = 'rejected' then now() else null end,
      rejected_by_employee_id = case when p_decision = 'rejected' then v_admin else null end
  where id = v_app.id;

  if p_decision = 'approved' and v_app.application_type = 'paid_leave' then
    perform public.recalculate_paid_leave_balance(v_balance_id);
  elsif p_decision = 'approved' and v_app.application_type = 'comp_leave' then
    for v_record_id in select holiday_work_record_id from public.comp_leave_allocations
      where application_id = v_app.id order by holiday_work_record_id
    loop
      perform public.recalculate_holiday_work_record(v_record_id);
    end loop;
  end if;

  insert into public.application_status_history
    (application_id, from_status, to_status, comment, changed_by_employee_id)
  values (v_app.id, v_app.status, p_decision, nullif(trim(p_comment), ''), v_admin);
end;
$$;

create or replace function public.cancel_application(
  p_application_id bigint,
  p_comment text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_app public.applications%rowtype;
  v_actor bigint;
  v_balance_id bigint;
  v_record_id bigint;
begin
  v_actor := public.current_employee_id();
  select * into v_app from public.applications
  where id = p_application_id for update;
  if not found then raise exception 'application_not_found'; end if;

  if v_app.status = 'cancelled' then return; end if;
  if not public.is_application_admin() then
    if v_app.employee_id <> v_actor then raise exception 'forbidden'; end if;
    if v_app.status not in ('draft', 'submitted', 'revision_required') then
      raise exception 'admin_required_to_cancel_approved_application';
    end if;
  end if;

  if v_app.status = 'approved' and v_app.application_type = 'paid_leave' then
    select balance_id into v_balance_id
    from public.paid_leave_balance_transactions
    where application_id = v_app.id and transaction_type = 'application_usage'
    for update;
    update public.paid_leave_balance_transactions
      set active = false
      where application_id = v_app.id and transaction_type = 'application_usage';
  elsif v_app.status = 'approved' and v_app.application_type = 'comp_leave' then
    perform 1 from public.holiday_work_records h
    where h.id in (select holiday_work_record_id from public.comp_leave_allocations
      where application_id = v_app.id)
    order by h.id for update;
  end if;

  update public.applications
  set status = 'cancelled', reviewer_comment = coalesce(nullif(trim(p_comment), ''), reviewer_comment),
      approved_at = null, approved_by_employee_id = null,
      rejected_at = null, rejected_by_employee_id = null
  where id = v_app.id;

  if v_balance_id is not null then
    perform public.recalculate_paid_leave_balance(v_balance_id);
  end if;
  if v_app.status = 'approved' and v_app.application_type = 'comp_leave' then
    for v_record_id in select holiday_work_record_id from public.comp_leave_allocations
      where application_id = v_app.id order by holiday_work_record_id
    loop
      perform public.recalculate_holiday_work_record(v_record_id);
    end loop;
  end if;

  insert into public.application_status_history
    (application_id, from_status, to_status, comment, changed_by_employee_id)
  values (v_app.id, v_app.status, 'cancelled', nullif(trim(p_comment), ''), v_actor);
end;
$$;

-- --------------------------------------------------------------------------
-- 5. 管理者用残数・休日出勤RPC
-- --------------------------------------------------------------------------

create or replace function public.set_paid_leave_opening_balance(
  p_employee_id bigint,
  p_fiscal_year integer,
  p_granted_days numeric,
  p_carried_days numeric,
  p_imported_used_days numeric,
  p_adjustment_days numeric default 0,
  p_base_date date default null
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_admin bigint; v_balance_id bigint;
begin
  if not public.is_application_admin() then raise exception 'admin_required'; end if;
  if p_granted_days < 0 or p_carried_days < 0 or p_imported_used_days < 0 then
    raise exception 'invalid_balance';
  end if;
  v_admin := public.current_employee_id();

  insert into public.paid_leave_balances
    (employee_id, fiscal_year, base_date, created_by_employee_id, updated_by_employee_id)
  values (p_employee_id, p_fiscal_year, p_base_date, v_admin, v_admin)
  on conflict (employee_id, fiscal_year) do update
    set base_date = excluded.base_date, updated_by_employee_id = v_admin
  returning id into v_balance_id;

  insert into public.paid_leave_balance_transactions
    (balance_id, transaction_type, days, source_key, reason, created_by_employee_id)
  values
    (v_balance_id, 'grant', p_granted_days, 'opening:grant', '年度初期登録', v_admin),
    (v_balance_id, 'carryover', p_carried_days, 'opening:carryover', '年度初期登録', v_admin),
    (v_balance_id, 'imported_usage', -p_imported_used_days, 'opening:imported_usage', '経理データ取込', v_admin),
    (v_balance_id, 'adjustment', p_adjustment_days, 'opening:adjustment', '初期調整', v_admin)
  on conflict (balance_id, source_key) do update
    set days = excluded.days, active = true, reason = excluded.reason;

  perform public.recalculate_paid_leave_balance(v_balance_id);
  return v_balance_id;
end;
$$;

create or replace function public.register_holiday_work(
  p_employee_id bigint,
  p_work_date date,
  p_earned_days numeric,
  p_site_id bigint default null,
  p_note text default null,
  p_source_type text default 'manual',
  p_source_attendance_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_admin bigint; v_id bigint;
begin
  if not public.is_application_admin() then raise exception 'admin_required'; end if;
  if p_earned_days <= 0 then raise exception 'invalid_earned_days'; end if;
  if p_source_type not in ('manual', 'attendance', 'import') then raise exception 'invalid_source_type'; end if;
  v_admin := public.current_employee_id();

  insert into public.holiday_work_records
    (employee_id, work_date, earned_days, used_days, remaining_days,
     site_id, note, source_type, source_attendance_id,
     created_by_employee_id, updated_by_employee_id)
  values
    (p_employee_id, p_work_date, p_earned_days, 0, p_earned_days,
     p_site_id, nullif(trim(p_note), ''), p_source_type, p_source_attendance_id,
     v_admin, v_admin)
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.update_holiday_work(
  p_record_id bigint,
  p_work_date date,
  p_earned_days numeric,
  p_site_id bigint default null,
  p_note text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_record public.holiday_work_records%rowtype;
  v_approved_used numeric(6,2);
  v_committed_allocated numeric(6,2);
begin
  if not public.is_application_admin() then raise exception 'admin_required'; end if;
  if p_earned_days <= 0 then raise exception 'invalid_earned_days'; end if;

  select * into v_record from public.holiday_work_records
  where id = p_record_id for update;
  if not found then raise exception 'holiday_work_record_not_found'; end if;
  if v_record.status = 'cancelled' then raise exception 'holiday_work_record_already_cancelled'; end if;

  select
    coalesce(sum(ca.allocated_days) filter (where a.status = 'approved'), 0),
    coalesce(sum(ca.allocated_days) filter (where a.status in ('submitted', 'approved')), 0)
  into v_approved_used, v_committed_allocated
  from public.comp_leave_allocations ca
  join public.applications a on a.id = ca.application_id
  where ca.holiday_work_record_id = p_record_id;

  if p_earned_days < v_committed_allocated then
    raise exception 'earned_days_cannot_be_less_than_submitted_or_approved_comp_leave_allocation';
  end if;

  update public.holiday_work_records
  set work_date = p_work_date,
      earned_days = p_earned_days,
      used_days = v_approved_used,
      remaining_days = p_earned_days - v_approved_used,
      site_id = p_site_id,
      note = nullif(trim(p_note), ''),
      updated_by_employee_id = public.current_employee_id()
  where id = p_record_id;
end;
$$;

create or replace function public.cancel_holiday_work(
  p_record_id bigint,
  p_comment text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_record public.holiday_work_records%rowtype;
  v_committed_allocated numeric(6,2);
begin
  if not public.is_application_admin() then raise exception 'admin_required'; end if;

  select * into v_record from public.holiday_work_records
  where id = p_record_id for update;
  if not found then raise exception 'holiday_work_record_not_found'; end if;
  if v_record.status = 'cancelled' then return; end if;

  select coalesce(sum(ca.allocated_days), 0) into v_committed_allocated
  from public.comp_leave_allocations ca
  join public.applications a on a.id = ca.application_id
  where ca.holiday_work_record_id = p_record_id
    and a.status in ('submitted', 'approved');

  if v_committed_allocated > 0 then
    raise exception 'holiday_work_allocated_to_submitted_or_approved_application_cannot_cancel';
  end if;

  update public.holiday_work_records
  set status = 'cancelled',
      used_days = 0,
      remaining_days = earned_days,
      note = case when nullif(trim(p_comment), '') is null then note
        else concat_ws(E'\n', note, '取消理由: ' || trim(p_comment)) end,
      updated_by_employee_id = public.current_employee_id()
  where id = p_record_id;
end;
$$;

-- --------------------------------------------------------------------------
-- 6. INDEX
-- --------------------------------------------------------------------------

create index if not exists applications_employee_created_idx
  on public.applications (employee_id, created_at desc);
create index if not exists applications_status_submitted_idx
  on public.applications (status, submitted_at) where status = 'submitted';
create index if not exists applications_type_status_idx
  on public.applications (application_type, status);
create index if not exists application_status_history_application_idx
  on public.application_status_history (application_id, changed_at);
create index if not exists paid_leave_balances_employee_year_idx
  on public.paid_leave_balances (employee_id, fiscal_year desc);
create index if not exists paid_leave_transactions_balance_idx
  on public.paid_leave_balance_transactions (balance_id, active);
create index if not exists holiday_work_employee_date_idx
  on public.holiday_work_records (employee_id, work_date desc);
create index if not exists holiday_work_remaining_idx
  on public.holiday_work_records (employee_id, work_date)
  where status = 'active' and remaining_days > 0;
create index if not exists comp_leave_allocations_record_idx
  on public.comp_leave_allocations (holiday_work_record_id, application_id);
create index if not exists comp_leave_dates_application_order_idx
  on public.comp_leave_dates (application_id, display_order, leave_date);

-- --------------------------------------------------------------------------
-- 7. RLS
-- --------------------------------------------------------------------------

alter table public.application_types enable row level security;
alter table public.applications enable row level security;
alter table public.application_status_history enable row level security;
alter table public.paid_leave_application_details enable row level security;
alter table public.comp_leave_application_details enable row level security;
alter table public.comp_leave_dates enable row level security;
alter table public.paid_leave_balances enable row level security;
alter table public.paid_leave_balance_transactions enable row level security;
alter table public.holiday_work_records enable row level security;
alter table public.comp_leave_allocations enable row level security;

-- このSQLをレビュー環境で再実行できるよう、今回定義するPolicyだけを作り直します。
do $$
declare v_policy record;
begin
  for v_policy in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and policyname in (
        'application_types_authenticated_select',
        'applications_self_or_admin_select', 'applications_self_insert',
        'applications_self_draft_update', 'application_history_self_or_admin_select',
        'paid_leave_details_self_or_admin_select', 'paid_leave_details_self_draft_insert',
        'paid_leave_details_self_draft_update', 'comp_leave_details_self_or_admin_select',
        'comp_leave_details_self_draft_insert', 'comp_leave_details_self_draft_update',
        'comp_leave_dates_self_or_admin_select', 'comp_leave_dates_self_draft_insert',
        'comp_leave_dates_self_draft_update', 'comp_leave_dates_self_draft_delete',
        'paid_leave_balances_self_or_admin_select', 'paid_leave_transactions_admin_select',
        'holiday_work_records_self_or_admin_select',
        'comp_leave_allocations_self_or_admin_select',
        'comp_leave_allocations_self_draft_insert',
        'comp_leave_allocations_self_draft_update',
        'comp_leave_allocations_self_draft_delete'
      )
  loop
    execute format('drop policy %I on %I.%I',
      v_policy.policyname, v_policy.schemaname, v_policy.tablename);
  end loop;
end;
$$;

create policy application_types_authenticated_select
on public.application_types for select to authenticated using (active = true);

create policy applications_self_or_admin_select
on public.applications for select to authenticated
using (employee_id = public.current_employee_id() or public.is_application_admin());

create policy applications_self_insert
on public.applications for insert to authenticated
with check (
  employee_id = public.current_employee_id()
  and created_by_employee_id = public.current_employee_id()
  and status = 'draft'
);

create policy applications_self_draft_update
on public.applications for update to authenticated
using (employee_id = public.current_employee_id() and status = 'draft')
with check (employee_id = public.current_employee_id() and status = 'draft');

create policy application_history_self_or_admin_select
on public.application_status_history for select to authenticated
using (exists (
  select 1 from public.applications a
  where a.id = application_id
    and (a.employee_id = public.current_employee_id() or public.is_application_admin())
));

create policy paid_leave_details_self_or_admin_select
on public.paid_leave_application_details for select to authenticated
using (exists (
  select 1 from public.applications a where a.id = application_id
    and (a.employee_id = public.current_employee_id() or public.is_application_admin())
));
create policy paid_leave_details_self_draft_insert
on public.paid_leave_application_details for insert to authenticated
with check (exists (
  select 1 from public.applications a where a.id = application_id
    and a.employee_id = public.current_employee_id() and a.status = 'draft'
    and a.application_type = 'paid_leave'
));
create policy paid_leave_details_self_draft_update
on public.paid_leave_application_details for update to authenticated
using (exists (select 1 from public.applications a where a.id = application_id
  and a.employee_id = public.current_employee_id() and a.status = 'draft'))
with check (exists (select 1 from public.applications a where a.id = application_id
  and a.employee_id = public.current_employee_id() and a.status = 'draft'));

create policy comp_leave_details_self_or_admin_select
on public.comp_leave_application_details for select to authenticated
using (exists (select 1 from public.applications a where a.id = application_id
  and (a.employee_id = public.current_employee_id() or public.is_application_admin())));
create policy comp_leave_details_self_draft_insert
on public.comp_leave_application_details for insert to authenticated
with check (exists (select 1 from public.applications a where a.id = application_id
  and a.employee_id = public.current_employee_id() and a.status = 'draft'
  and a.application_type = 'comp_leave'));
create policy comp_leave_details_self_draft_update
on public.comp_leave_application_details for update to authenticated
using (exists (select 1 from public.applications a where a.id = application_id
  and a.employee_id = public.current_employee_id() and a.status = 'draft'))
with check (exists (select 1 from public.applications a where a.id = application_id
  and a.employee_id = public.current_employee_id() and a.status = 'draft'));

create policy comp_leave_dates_self_or_admin_select
on public.comp_leave_dates for select to authenticated
using (exists (select 1 from public.applications a where a.id = application_id
  and (a.employee_id = public.current_employee_id() or public.is_application_admin())));
create policy comp_leave_dates_self_draft_insert
on public.comp_leave_dates for insert to authenticated
with check (exists (select 1 from public.applications a where a.id = application_id
  and a.employee_id = public.current_employee_id() and a.status = 'draft'
  and a.application_type = 'comp_leave'));
create policy comp_leave_dates_self_draft_update
on public.comp_leave_dates for update to authenticated
using (exists (select 1 from public.applications a where a.id = application_id
  and a.employee_id = public.current_employee_id() and a.status = 'draft'))
with check (exists (select 1 from public.applications a where a.id = application_id
  and a.employee_id = public.current_employee_id() and a.status = 'draft'));
create policy comp_leave_dates_self_draft_delete
on public.comp_leave_dates for delete to authenticated
using (exists (select 1 from public.applications a where a.id = application_id
  and a.employee_id = public.current_employee_id() and a.status = 'draft'));

create policy paid_leave_balances_self_or_admin_select
on public.paid_leave_balances for select to authenticated
using (employee_id = public.current_employee_id() or public.is_application_admin());

create policy paid_leave_transactions_admin_select
on public.paid_leave_balance_transactions for select to authenticated
using (public.is_application_admin());

create policy holiday_work_records_self_or_admin_select
on public.holiday_work_records for select to authenticated
using (employee_id = public.current_employee_id() or public.is_application_admin());

create policy comp_leave_allocations_self_or_admin_select
on public.comp_leave_allocations for select to authenticated
using (exists (select 1 from public.applications a where a.id = application_id
  and (a.employee_id = public.current_employee_id() or public.is_application_admin())));
create policy comp_leave_allocations_self_draft_insert
on public.comp_leave_allocations for insert to authenticated
with check (
  exists (select 1 from public.applications a where a.id = application_id
    and a.employee_id = public.current_employee_id() and a.status = 'draft'
    and a.application_type = 'comp_leave')
  and exists (select 1 from public.holiday_work_records h
    where h.id = holiday_work_record_id
      and h.employee_id = public.current_employee_id()
      and h.status = 'active')
);
create policy comp_leave_allocations_self_draft_update
on public.comp_leave_allocations for update to authenticated
using (exists (select 1 from public.applications a where a.id = application_id
  and a.employee_id = public.current_employee_id() and a.status = 'draft'))
with check (
  exists (select 1 from public.applications a where a.id = application_id
    and a.employee_id = public.current_employee_id() and a.status = 'draft')
  and exists (select 1 from public.holiday_work_records h
    where h.id = holiday_work_record_id and h.employee_id = public.current_employee_id())
);
create policy comp_leave_allocations_self_draft_delete
on public.comp_leave_allocations for delete to authenticated
using (exists (select 1 from public.applications a where a.id = application_id
  and a.employee_id = public.current_employee_id() and a.status = 'draft'));

-- paid_leave_balance_transactions は本人にも直接公開しません。
-- application_status_history と同様、履歴の UPDATE / DELETE policy は作成しません。

-- --------------------------------------------------------------------------
-- 8. GRANT / REVOKE（RLSだけでなく列権限でも承認情報を保護）
-- --------------------------------------------------------------------------

revoke all on table public.application_types, public.applications,
  public.application_status_history, public.paid_leave_application_details,
  public.comp_leave_application_details, public.comp_leave_dates,
  public.paid_leave_balances,
  public.paid_leave_balance_transactions, public.holiday_work_records,
  public.comp_leave_allocations from anon, authenticated;

grant select on public.application_types, public.applications,
  public.application_status_history, public.paid_leave_application_details,
  public.comp_leave_application_details, public.comp_leave_dates,
  public.paid_leave_balances,
  public.paid_leave_balance_transactions,
  public.holiday_work_records, public.comp_leave_allocations to authenticated;

grant insert (application_type, employee_id, applicant_note, created_by_employee_id)
  on public.applications to authenticated;
grant update (applicant_note) on public.applications to authenticated;

grant insert (application_id, site_id, start_date, end_date, days, day_part, reason),
  update (site_id, start_date, end_date, days, day_part, reason)
  on public.paid_leave_application_details to authenticated;
grant insert (application_id, note), update (note)
  on public.comp_leave_application_details to authenticated;
grant insert (application_id, leave_date, days, display_order),
  update (leave_date, days, display_order), delete
  on public.comp_leave_dates to authenticated;
grant insert (application_id, holiday_work_record_id, allocated_days),
  update (allocated_days), delete
  on public.comp_leave_allocations to authenticated;

grant usage, select on sequence public.applications_id_seq to authenticated;
grant usage, select on sequence public.comp_leave_dates_id_seq to authenticated;
grant usage, select on sequence public.comp_leave_allocations_id_seq to authenticated;

revoke all on function public.current_employee_id() from public;
revoke all on function public.is_application_admin() from public;
revoke all on function public.recalculate_paid_leave_balance(bigint) from public;
revoke all on function public.recalculate_holiday_work_record(bigint) from public;
revoke all on function public.validate_paid_leave_application(bigint) from public;
revoke all on function public.submit_application(bigint) from public;
revoke all on function public.reopen_application_draft(bigint) from public;
revoke all on function public.delete_draft_application(bigint) from public;
revoke all on function public.review_application(bigint,text,text) from public;
revoke all on function public.cancel_application(bigint,text) from public;
revoke all on function public.set_paid_leave_opening_balance(bigint,integer,numeric,numeric,numeric,numeric,date) from public;
revoke all on function public.register_holiday_work(bigint,date,numeric,bigint,text,text,bigint) from public;
revoke all on function public.update_holiday_work(bigint,date,numeric,bigint,text) from public;
revoke all on function public.cancel_holiday_work(bigint,text) from public;

grant execute on function public.current_employee_id() to authenticated;
grant execute on function public.is_application_admin() to authenticated;
grant execute on function public.submit_application(bigint) to authenticated;
grant execute on function public.reopen_application_draft(bigint) to authenticated;
grant execute on function public.delete_draft_application(bigint) to authenticated;
grant execute on function public.review_application(bigint,text,text) to authenticated;
grant execute on function public.cancel_application(bigint,text) to authenticated;
grant execute on function public.set_paid_leave_opening_balance(bigint,integer,numeric,numeric,numeric,numeric,date) to authenticated;
grant execute on function public.register_holiday_work(bigint,date,numeric,bigint,text,text,bigint) to authenticated;
grant execute on function public.update_holiday_work(bigint,date,numeric,bigint,text) to authenticated;
grant execute on function public.cancel_holiday_work(bigint,text) to authenticated;

commit;

-- ============================================================================
-- 2026年度初期登録例（実値へ置換して別途実行）
-- select public.set_paid_leave_opening_balance(
--   p_employee_id := 123,
--   p_fiscal_year := 2026,
--   p_granted_days := 20.0,
--   p_carried_days := 5.0,
--   p_imported_used_days := 3.0,
--   p_adjustment_days := 0.0,
--   p_base_date := date '2026-09-01'
-- );
-- ============================================================================
