-- Staff Portal Web Push delivery history.
-- This file is intentionally not applied automatically.

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  notification_type text not null
    check (notification_type in (
      'overdue_submission',
      'today_schedule',
      'tomorrow_schedule'
    )),
  employee_id bigint not null references public.employees(id) on delete cascade,
  push_subscription_id bigint not null references public.push_subscriptions(id) on delete cascade,
  notification_date date not null,
  target_month date,
  idempotency_key text not null,
  status text not null default 'pending'
    check (status in ('pending', 'sent', 'failed')),
  attempted_at timestamptz,
  sent_at timestamptz,
  error_message text,
  created_at timestamptz not null default now(),
  constraint notification_deliveries_idempotency_key_key
    unique (idempotency_key),
  constraint notification_deliveries_device_notification_key
    unique (
      notification_type,
      employee_id,
      push_subscription_id,
      notification_date
    )
);

create index if not exists notification_deliveries_employee_date_idx
  on public.notification_deliveries (employee_id, notification_date desc);

create index if not exists notification_deliveries_status_idx
  on public.notification_deliveries (status, attempted_at);

alter table public.notification_deliveries enable row level security;

-- No client policies are created. The scheduled Edge Function uses the
-- service-role client, and browser clients must not read or write this table.
revoke all on table public.notification_deliveries from anon, authenticated;
revoke all on sequence public.notification_deliveries_id_seq from anon, authenticated;
