-- Apply after site_master_preflight.sql, with a backup, as the table owner.
-- PostgreSQL 15+ (security_invoker view). All changes are transactional.
begin;
select pg_advisory_xact_lock(726314920);
lock table public.sites in share row exclusive mode;
create temporary table site_master_original on commit drop as
select id, to_jsonb(s)-'client_id'-'client_site_order' as original from public.sites s;

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null check (trim(name) <> ''),
  code text not null check (trim(code) <> ''),
  visible boolean not null default true,
  display_order integer not null check (display_order > 0)
);
-- Company suffix normalization prevents common spelling variants on new masters.
create or replace function public.client_name_key(p_name text)
returns text language sql immutable strict set search_path = '' as $$
  select lower(regexp_replace(replace(replace(replace(replace(
    normalize(p_name, NFKC), '株式会社',''), '有限会社',''), '(株)',''), '(有)',''),
    '[[:space:]　]', '', 'g'))
$$;
create unique index if not exists clients_name_key_unique on public.clients(public.client_name_key(name));
create unique index if not exists clients_code_unique on public.clients(lower(trim(code)));
alter table public.sites add column if not exists client_id bigint references public.clients(id);
alter table public.sites add column if not exists client_site_order integer;

-- Initial names/order are migration data ONLY, never application constants.
create temporary table initial_clients(name text, position integer) on commit drop;
insert into initial_clients
select * from (values ('三機工業',1),('STS',2),('三晃空調',3),('朝日工業社',4),('西原衛生',5),('自社',6)) seed(name,position)
where not exists(select 1 from public.clients);
create temporary table legacy_clients on commit drop as
select s.id, s.client_code,
  case public.client_name_key(s.client_name)
    when '三機' then '三機工業'
    else coalesce((select i.name from initial_clients i
      where public.client_name_key(i.name)=public.client_name_key(s.client_name)), trim(s.client_name))
  end as name
from public.sites s where s.client_id is null and nullif(trim(s.client_name),'') is not null;
do $$
declare r record; v_code text; v_n integer := 0; v_order integer;
begin
  if exists (select 1 from legacy_clients group by public.client_name_key(name)
    having count(distinct lower(nullif(trim(client_code),''))) > 1) then
    raise exception '同一元請に複数の元請コードがあります。移行用の対応表を確認してください（既存データは変更しないでください）';
  end if;
  for r in
    select name, min(position) as position from (
      select name, position from initial_clients union all select name, 1000 from legacy_clients
    ) x group by name order by min(position), name
  loop
    if exists(select 1 from public.clients c where public.client_name_key(c.name)=public.client_name_key(r.name)) then continue; end if;
    select min(nullif(trim(client_code),'')) into v_code from legacy_clients
      where public.client_name_key(name)=public.client_name_key(r.name);
    if v_code is null then
      loop
        v_n := v_n + 1;
        v_code := 'C' || case when v_n<1000 then lpad(v_n::text,3,'0') else v_n::text end;
        exit when not exists(select 1 from public.clients where lower(code)=lower(v_code))
          and not exists(select 1 from legacy_clients where lower(trim(client_code))=lower(v_code));
      end loop;
    end if;
    if exists(select 1 from public.clients where lower(trim(code))=lower(v_code)) then
      raise exception '元請コード % が複数の元請名に対応しています。移行用の対応表を確認してください', v_code;
    end if;
    select coalesce(max(display_order),0)+1 into v_order from public.clients;
    insert into public.clients(name,code,display_order) values(r.name,v_code,v_order);
  end loop;
end $$;
update public.sites s set client_id=c.id from legacy_clients l, public.clients c
where s.id=l.id and public.client_name_key(c.name)=public.client_name_key(l.name) and s.client_id is null;
with ranked as (
  select id, row_number() over(partition by client_id order by display_order nulls last,display_name,id) as n
  from public.sites
) update public.sites s set client_site_order=r.n from ranked r
where s.id=r.id and s.client_site_order is null;
-- Existing duplicates cause a safe rollback, never an automatic renumbering.
create unique index if not exists sites_input_code_master_unique on public.sites(input_code)
where input_code is not null and input_code <> '';
create index if not exists sites_client_order_idx on public.sites(client_id,client_site_order,id);

create or replace function public.is_site_master_admin()
returns boolean language sql stable security definer set search_path = '' as $$
  select count(*)=1 and coalesce(bool_and(admin_scope is not null and admin_scope not in ('','none','tool_admin')),false)
  from public.employees where auth_user_id=auth.uid() and active=true
$$;
alter table public.clients enable row level security;
drop policy if exists clients_read on public.clients;
create policy clients_read on public.clients for select to authenticated
using (exists(select 1 from public.employees where auth_user_id=auth.uid() and active=true));
revoke all on public.clients from anon, authenticated;
grant select on public.clients to authenticated;

create or replace function public.prepare_site_master()
returns trigger language plpgsql security definer set search_path = '' as $$
declare c public.clients%rowtype; n numeric; candidate text; code_prefix text;
begin
  perform pg_advisory_xact_lock(726314920);
  if tg_op='UPDATE' then
    if new.id is distinct from old.id or new.input_code is distinct from old.input_code then
      raise exception '既存の現場ID・入力コードは変更できません';
    end if;
  end if;
  if tg_op='INSERT' or new.client_id is distinct from old.client_id then
    select * into c from public.clients where id=new.client_id;
    if not found or not c.visible then raise exception '表示中の元請を選択してください'; end if;
    new.client_name := c.name; new.client_code := c.code;
    select coalesce(max(client_site_order),0)+1 into new.client_site_order
      from public.sites where client_id=new.client_id;
  end if;
  if tg_op='INSERT' then
    if new.site_type is null or new.site_type not in ('一般','雑工事') then
      raise exception '現場種別を選択してください';
    end if;
    code_prefix := c.code || case when new.site_type='雑工事' then 'Z' else '' end;
    -- Independent series: S005 -> S006, SZ002 -> SZ003. Never fill gaps.
    -- Scan all existing codes, including hidden sites or rows whose type was later edited.
    select coalesce(max(substring(input_code from length(code_prefix)+1)::numeric),0)+1 into n
    from public.sites where left(input_code,length(code_prefix))=code_prefix
      and substring(input_code from length(code_prefix)+1) ~ '^[0-9]+$';
    loop
      candidate := code_prefix || case when n<1000 then lpad(n::text,3,'0') else n::text end;
      exit when not exists(select 1 from public.sites where input_code=candidate);
      n := n+1;
    end loop;
    new.input_code := candidate;
    select coalesce(max(display_order),0)+1 into new.display_order from public.sites;
  end if;
  return new;
end $$;
drop trigger if exists prepare_site_master on public.sites;
create trigger prepare_site_master before insert or update on public.sites
for each row execute function public.prepare_site_master();

create or replace function public.save_client_master(p_id bigint, p_name text, p_code text, p_visible boolean)
returns public.clients language plpgsql security definer set search_path = '' as $$
declare result public.clients; n integer;
begin
  if not public.is_site_master_admin() then raise exception '管理者権限が必要です'; end if;
  perform pg_advisory_xact_lock(726314920);
  if nullif(trim(p_name),'') is null then raise exception '元請名を入力してください'; end if;
  if nullif(trim(p_code),'') is null then raise exception '元請コードを入力してください'; end if;
  if p_visible is null then raise exception '表示状態を選択してください'; end if;
  if p_id is null then
    select coalesce(max(display_order),0)+1 into n from public.clients;
    insert into public.clients(name,code,visible,display_order)
    values(trim(p_name),trim(p_code),p_visible,n) returning * into result;
  else
    update public.clients set name=trim(p_name),code=trim(p_code),visible=p_visible
    where id=p_id returning * into result;
    if not found then raise exception '元請が見つかりません。再読み込みしてください'; end if;
  end if;
  return result;
exception when unique_violation then raise exception '同じ元請名または元請コードが登録されています';
end $$;

create or replace function public.save_site_master(p_id bigint, p_client_id bigint,
  p_display_name text, p_construction_no text, p_official_name text, p_visible boolean, p_site_type text)
returns public.sites language plpgsql security definer set search_path = '' as $$
declare result public.sites;
begin
  if not public.is_site_master_admin() then raise exception '管理者権限が必要です'; end if;
  perform pg_advisory_xact_lock(726314920);
  if nullif(trim(p_display_name),'') is null then raise exception '表示名を入力してください'; end if;
  if p_client_id is null then raise exception '元請を選択してください'; end if;
  if nullif(trim(p_construction_no),'') is null then raise exception '工事番号を入力してください'; end if;
  if nullif(trim(p_official_name),'') is null then raise exception '正式名称を入力してください'; end if;
  if p_visible is null or p_site_type is null or p_site_type not in ('一般','雑工事') then raise exception '表示状態・現場種別を確認してください'; end if;
  if p_id is null then
    insert into public.sites(client_id,display_name,construction_no,official_name,visible,site_type)
    values(p_client_id,trim(p_display_name),trim(p_construction_no),trim(p_official_name),p_visible,p_site_type)
    returning * into result;
  else
    update public.sites set client_id=p_client_id,display_name=trim(p_display_name),
      construction_no=trim(p_construction_no),official_name=trim(p_official_name),visible=p_visible,site_type=p_site_type
    where id=p_id returning * into result;
    if not found then raise exception '現場が見つかりません。再読み込みしてください'; end if;
  end if;
  return result;
end $$;

-- Atomic swap + dense renumber. expected_ids includes hidden rows and detects stale screens.
create or replace function public.move_master_item(p_kind text, p_id bigint, p_direction integer, p_expected_ids bigint[])
returns void language plpgsql security definer set search_path = '' as $$
declare ids bigint[]; group_id bigint; pos integer; target integer; swap bigint;
begin
  if not public.is_site_master_admin() then raise exception '管理者権限が必要です'; end if;
  perform pg_advisory_xact_lock(726314920);
  if p_direction is null or p_direction not in (-1,1) then raise exception '移動方向が不正です'; end if;
  if p_kind='client' then
    select array_agg(id order by display_order,id) into ids from public.clients;
  elsif p_kind='site' then
    select client_id into group_id from public.sites where id=p_id;
    if not found then raise exception '現場が見つかりません'; end if;
    select array_agg(id order by client_site_order nulls last,display_order nulls last,display_name,id)
    into ids from public.sites where client_id is not distinct from group_id;
  else raise exception '対象が不正です'; end if;
  if ids is distinct from p_expected_ids then raise exception '一覧が更新されています。再読み込みしてから並び替えてください'; end if;
  pos := array_position(ids,p_id); target := pos+p_direction;
  if pos is null then raise exception '対象が見つかりません'; end if;
  if target<1 or target>array_length(ids,1) then return; end if;
  swap := ids[target]; ids[target] := ids[pos]; ids[pos] := swap;
  if p_kind='client' then
    update public.clients c set display_order=x.n from unnest(ids) with ordinality x(id,n) where c.id=x.id;
  else
    update public.sites s set client_site_order=x.n from unnest(ids) with ordinality x(id,n) where s.id=x.id;
  end if;
end $$;

-- Underlying sites RLS still applies. Hidden clients do NOT filter existing sites.
create or replace view public.site_master_order with (security_invoker=true) as
select s.*, c.display_order as client_display_order, c.name as master_client_name
from public.sites s left join public.clients c on c.id=s.client_id;
grant select on public.site_master_order to authenticated;
revoke all on function public.prepare_site_master() from public, anon, authenticated;
revoke all on function public.is_site_master_admin() from public, anon;
revoke all on function public.save_client_master(bigint,text,text,boolean) from public, anon;
revoke all on function public.save_site_master(bigint,bigint,text,text,text,boolean,text) from public, anon;
revoke all on function public.move_master_item(text,bigint,integer,bigint[]) from public, anon;
grant execute on function public.is_site_master_admin() to authenticated;
grant execute on function public.save_client_master(bigint,text,text,boolean) to authenticated;
grant execute on function public.save_site_master(bigint,bigint,text,text,text,boolean,text) to authenticated;
grant execute on function public.move_master_item(text,bigint,integer,bigint[]) to authenticated;
do $$ begin
  if exists (
    select 1 from site_master_original o full join public.sites s on s.id=o.id
    where o.original is distinct from (to_jsonb(s)-'client_id'-'client_site_order')
  ) then raise exception '移行前後で既存現場項目が変化したためロールバックします'; end if;
end $$;
notify pgrst, 'reload schema';
commit;
