// PGLITE_MODULE=/absolute/path/to/@electric-sql/pglite/dist/index.js node tests/site-master-db.test.mjs
// Isolated PostgreSQL; no connection to production.
import { readFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';
const { PGlite } = await import(process.env.PGLITE_MODULE ? pathToFileURL(process.env.PGLITE_MODULE).href : '@electric-sql/pglite');
const migration = await readFile(new URL('../supabase/site_master.sql', import.meta.url), 'utf8');
const db = new PGlite();
const q = async (sql, params=[]) => (await db.query(sql, params)).rows;
const setup = `
  create role anon; create role authenticated;
  create schema auth;
  create function auth.uid() returns uuid language sql stable as
    $$ select nullif(current_setting('test.uid',true),'')::uuid $$;
  create table employees(id bigint primary key, auth_user_id uuid, active boolean, admin_scope text);
  insert into employees values (1,'00000000-0000-0000-0000-000000000001',true,'all'),
    (2,'00000000-0000-0000-0000-000000000002',true,'none'),
    (3,'00000000-0000-0000-0000-000000000003',true,'tool_admin');
  grant usage on schema auth to authenticated;
  grant select on employees to authenticated;
  create table sites(id bigint generated by default as identity primary key,
    display_order integer not null, input_code text not null, client_code text,
    construction_no text, client_name text, display_name text, official_name text,
    visible boolean, site_type text, unrelated text default 'preserved');
  alter table sites enable row level security;
  create policy read_sites on sites for select to authenticated using(id<>5);
  grant select on sites to authenticated;
  insert into sites(display_order,input_code,client_code,construction_no,client_name,display_name,official_name,visible,site_type) values
    (10,'A001','A','K-1','三機工業','現場A','正式A',true,'一般'),
    (30,'A010','A','K-2','三機工業㈱','現場B','正式B',false,'一般'),
    (20,'B001','B','K-3','三晃空調','現場C','正式C',true,'一般'),
    (40,'LEGACY','','K-4','','旧現場','旧現場',true,'一般'),
    (50,'X100','X','K-5','追加元請','現場D','正式D',true,'雑工事');
  create table attendance(id bigint,site_id bigint references sites(id));
  create table tools(id bigint,current_site_id bigint references sites(id));
  insert into attendance values(1,1),(2,2); insert into tools values(1,1);
  select set_config('test.uid','00000000-0000-0000-0000-000000000001',false);
`;
await db.exec(setup);
const originals = await q('select * from sites order by id');
await db.exec(migration);
for (const row of await q('select * from sites order by id')) {
  const {client_id,client_site_order,...legacy}=row;
  assert.deepEqual(legacy, originals.find(x=>x.id===row.id));
}
assert.deepEqual((await q('select name from clients order by display_order limit 6')).map(x=>x.name),
  ['三機工業','STS','三晃空調','朝日工業社','西原衛生','自社']);
assert.equal((await q('select count(distinct client_id)::int n from sites where id in (1,2)'))[0].n,1);
const a=(await q("select id from clients where code='A'"))[0].id;
const b=(await q("select id from clients where code='B'"))[0].id;
const clientIds=async()=> (await q('select id from clients order by display_order,id')).map(x=>x.id);
const siteIds=async id=>(await q('select id from sites where client_id=$1 order by client_site_order,display_order,display_name,id',[id])).map(x=>x.id);
const save=async(id,client,construction='NEW')=>(await q("select * from save_site_master($1,$2,'新現場',$3,'新正式',true,'一般')",[id,client,construction]))[0];
const fails=async(sql,params,pattern)=>assert.rejects(q(sql,params),pattern);
await db.exec('set role authenticated');
const added=await save(null,a);
assert.equal(added.input_code,'A011'); assert.equal(added.client_site_order,3); assert.equal(added.client_code,'A');
assert.equal(added.display_order,51);
await q("select move_master_item('site',$1,-1,$2::bigint[])",[added.id,await siteIds(a)]);
assert.deepEqual(await siteIds(a),[1,added.id,2]);
await fails("select move_master_item('site',$1,-1,$2::bigint[])",[added.id,[1,2,added.id]],/一覧が更新/);
await q("select move_master_item('client',$1,-1,$2::bigint[])",[b,await clientIds()]);
assert.deepEqual(await siteIds(a),[1,added.id,2]);
assert.equal((await q('select display_order from sites where id=1'))[0].display_order,10);
await q("select save_client_master($1,'三機工業','A',false)",[a]);
assert.equal((await q('select visible from sites where id=1'))[0].visible,true);
assert.ok((await q('select id from site_master_order')).some(x=>x.id===1));
assert.ok(!(await q('select id from site_master_order')).some(x=>x.id===5)); // Invoker view keeps sites RLS.
await assert.rejects(save(null,a),/表示中の元請/);
const edited=await save(1,a);
assert.equal(edited.input_code,'A001'); assert.equal(edited.client_name,'三機工業');
await fails("select save_client_master(null,'三機工業株式会社','OTHER',true)",[],/同じ元請名/);
await fails("select save_client_master(null,'別会社','B',true)",[],/同じ元請名/);
await assert.rejects(save(null,b,''),/工事番号/);
await q("select set_config('test.uid','00000000-0000-0000-0000-000000000002',false)");
await assert.rejects(save(null,b),/管理者権限/);
await fails("select save_client_master(null,'不正','NO',true)",[],/管理者権限/);
await fails("select move_master_item('client',$1,1,$2::bigint[])",[b,await clientIds()],/管理者権限/);
await q("select set_config('test.uid','00000000-0000-0000-0000-000000000003',false)");
await assert.rejects(save(null,b),/管理者権限/);
await db.exec('reset role');
await fails("update sites set input_code='CHANGED' where id=1",[],/変更できません/);
await fails('update sites set id=999 where id=1',[],/変更できません/);
await q("select set_config('test.uid','00000000-0000-0000-0000-000000000001',false)");
await q("select save_client_master($1,'元請の新名称','A',false)",[a]);
const beforeRerun=await q('select * from sites order by id'), clientsBefore=await q('select * from clients order by id');
await db.exec(migration);
assert.deepEqual(await q('select * from sites order by id'),beforeRerun);
assert.deepEqual(await q('select * from clients order by id'),clientsBefore);
assert.deepEqual(await q('select * from attendance order by id'),[{id:1,site_id:1},{id:2,site_id:2}]);
assert.deepEqual(await q('select * from tools'),[{id:1,current_site_id:1}]);
// Code overlap across client prefixes must not cause duplicate input codes.
await db.exec("insert into sites(client_id,display_name,site_type) values ("+b+",'direct','一般')");
assert.equal((await q("select input_code from sites where display_name='direct'"))[0].input_code,'B002');
const moved=await save(1,b);
assert.equal(moved.id,1); assert.equal(moved.input_code,'A001'); assert.equal(moved.client_code,'B');
assert.equal((await siteIds(b)).at(-1),1);
await db.close();
console.log('PASS site-master migration, preservation, numbering, visibility, reordering, stale state, RLS and permissions');
for (const [name,change,error] of [
  ['ambiguous client code',"update sites set client_code='OTHER' where id=2",/複数の元請コード/],
  ['shared code across names',"update sites set client_code='A' where id=3",/複数の元請名/],
  ['duplicate input code',"update sites set input_code='A001' where id=2",/unique index/]
]) {
  const isolated=new PGlite(); await isolated.exec(setup); await isolated.exec(change);
  const snapshot=(await isolated.query('select * from sites order by id')).rows;
  await assert.rejects(isolated.exec(migration),error); await isolated.exec('rollback');
  assert.deepEqual((await isolated.query('select * from sites order by id')).rows,snapshot);
  assert.equal((await isolated.query("select to_regclass('public.clients') as name")).rows[0].name,null);
  await isolated.close(); console.log(`PASS safe rollback: ${name}`);
}
const growth=new PGlite(); await growth.exec(setup);
await growth.exec("update sites set input_code='A999' where id=2");
await growth.exec(migration);
const generated=(await growth.query("select * from save_site_master(null,(select id from clients where code='A'),'1000','NO','NAME',true,'一般')")).rows[0];
assert.equal(generated.input_code,'A1000');
await growth.close(); console.log('PASS input code grows beyond three digits without truncation');

// Production preflight code families; legacy display_order duplicates are intentional.
const series=new PGlite(); await series.exec(setup);
await series.exec(`
  update sites set client_code='S',input_code='S001',display_order=1 where id=1;
  update sites set client_code='S',input_code='S005',display_order=1 where id=2;
  update sites set client_code='SK',input_code='SK002' where id=3;
  update sites set client_name='STS',client_code='ST',input_code='STZ001' where id=5;
  insert into sites(display_order,input_code,client_code,client_name,display_name,site_type,visible) values
    (7,'SZ001','S','三機工業','雑工事A','雑工事',true),
    (7,'SZ002','S','三機工業','雑工事B','雑工事',false),
    (8,'SKZ001','SK','三晃空調','雑工事C','雑工事',true),
    (9,'AS001','AS','朝日工業社','一般D','一般',true),
    (10,'AS002','AS','朝日工業社','一般E','一般',true),
    (11,'ASZ001','AS','朝日工業社','雑工事F','雑工事',true),
    (12,'NS001','NS','西原衛生','一般G','一般',true),
    (13,'SO001','SO','自社','一般H','一般',true),
    (14,'SOZ003','SO','自社','雑工事I','雑工事',true),
    (15,'SOZ004','SO','自社','雑工事J','雑工事',false);
`);
const seriesQuery=async(sql,params=[]) => (await series.query(sql,params)).rows;
const oldSeries=await seriesQuery('select * from sites order by id');
await series.exec(migration);
assert.deepEqual(await seriesQuery('select name,code,display_order from clients order by display_order'),[
  {name:'三機工業',code:'S',display_order:1},
  {name:'STS',code:'ST',display_order:2},
  {name:'三晃空調',code:'SK',display_order:3},
  {name:'朝日工業社',code:'AS',display_order:4},
  {name:'西原衛生',code:'NS',display_order:5},
  {name:'自社',code:'SO',display_order:6}
]);
assert.equal((await seriesQuery("select c.name from sites s join clients c on c.id=s.client_id where s.id=5"))[0].name,'STS');
for (const row of await seriesQuery('select * from sites order by id')) {
  const {client_id,client_site_order,...legacy}=row;
  assert.deepEqual(legacy,oldSeries.find(x=>x.id===row.id));
}
assert.deepEqual(await seriesQuery('select display_order,count(*)::int n from sites where display_order in (1,7) group by display_order order by display_order'),
  [{display_order:1,n:2},{display_order:7,n:2}]);
for (const [code,type,expected] of [
  ['S','一般','S006'],['S','雑工事','SZ003'],['S','一般','S007'],['S','雑工事','SZ004'],
  ['SK','一般','SK003'],['SK','雑工事','SKZ002'],['ST','雑工事','STZ002'],
  ['AS','一般','AS003'],['AS','雑工事','ASZ002'],['NS','一般','NS002'],
  ['SO','一般','SO002'],['SO','雑工事','SOZ005'],['NS','雑工事','NSZ001']
]) {
  const row=(await seriesQuery(`select * from save_site_master(null,
    (select id from clients where code=$1),'新規','番号','正式',true,$2)`,[code,type]))[0];
  assert.equal(row.input_code,expected);
}
const siblings=await seriesQuery("select id from sites where client_id=(select id from clients where code='S') order by client_site_order,display_order,display_name,id");
await seriesQuery("select move_master_item('site',$1,-1,$2::bigint[])",[siblings.at(-1).id,siblings.map(x=>x.id)]);
const positions=await seriesQuery("select client_site_order from sites where client_id=(select id from clients where code='S') order by client_site_order");
assert.deepEqual(positions.map(x=>x.client_site_order),positions.map((_,i)=>i+1));
for (const old of oldSeries) {
  const {client_id,client_site_order,...legacy}=(await seriesQuery('select * from sites where id=$1',[old.id]))[0];
  assert.deepEqual(legacy,old); // Includes id, input_code and duplicate legacy display_order.
}
// Editing the type preserves its old code; a later registration must still count that code.
await seriesQuery("select save_site_master(id,client_id,display_name,construction_no,official_name,visible,'雑工事') from sites where input_code='S007'");
assert.equal((await seriesQuery("select input_code from sites where input_code='S007'"))[0].input_code,'S007');
assert.equal((await seriesQuery("select * from save_site_master(null,(select id from clients where code='S'),'新規','番号','正式',true,'一般')"))[0].input_code,'S008');
await series.close();
console.log('PASS production series: S006 / SZ003 / SOZ005, independent maxima, hidden codes and duplicate legacy orders preserved');

const miscGrowth=new PGlite(); await miscGrowth.exec(setup);
await miscGrowth.exec("update sites set input_code='AZ999',site_type='雑工事' where id=2");
await miscGrowth.exec(migration);
assert.equal((await miscGrowth.query("select * from save_site_master(null,(select id from clients where code='A'),'1000','NO','NAME',true,'雑工事')")).rows[0].input_code,'AZ1000');
assert.equal((await miscGrowth.query("select * from save_site_master(null,(select id from clients where code='A'),'一般','NO','NAME',true,'一般')")).rows[0].input_code,'A002');
await miscGrowth.close(); console.log('PASS miscellaneous code grows to 1000 independently of general sites');
